## Question 1
For this question, calculate the win/loss ratio's correlation with the population of the city it is in for the **NHL** using **2018** data.

In [1]:
import pandas as pd
import numpy as np
import scipy.stats as stats
import re

nhl_df=pd.read_csv("nhl.csv")
cities=pd.read_html("wikipedia_data.html")[1]
cities=cities.iloc[:-1,[0,3,5,6,7,8]]
cities['NHL']=cities['NHL'].str.extract('([a-zA-Z0-9 \.]*)')
nhl_df['team']=nhl_df['team'].str.extract('([a-zA-Z0-9 \.]*)')

# for x in cities['NHL']:
#     print(nhl_df[nhl_df['team']==x])

nhl_df['team'].str.extract('(.*Sharks.*)').dropna()
nhl_df['year']=nhl_df['year'][nhl_df['year']==2018]
nhl_df2=nhl_df[nhl_df['year']==2018]
nhl_df2

,team,GP,W,L,OL,PTS,PTS%,GF,GA,SRS,SOS,RPt%,ROW,year,League
0,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,2018.0,NHL
1,Tampa Bay Lightning,82,54,23,5,113,.689,296,236,0.66,-0.07,.634,48,2018.0,NHL
2,Boston Bruins,82,50,20,12,112,.683,270,214,0.62,-0.07,.610,47,2018.0,NHL
3,Toronto Maple Leafs,82,49,26,7,105,.640,277,232,0.49,-0.06,.567,42,2018.0,NHL
4,Florida Panthers,82,44,30,8,96,.585,248,246,-0.01,-0.04,.537,41,2018.0,NHL
5,Detroit Red Wings,82,30,39,13,73,.445,217,255,-0.48,-0.01,.341,25,2018.0,NHL
6,Montreal Canadiens,82,29,40,13,71,.433,209,264,-0.68,0.00,.378,27,2018.0,NHL
7,Ottawa Senators,82,28,43,11,67,.409,221,291,-0.85,0.00,.372,26,2018.0,NHL
8,Buffalo Sabres,82,25,45,12,62,.378,199,280,-0.98,0.01,.311,24,2018.0,NHL
9,Metropolitan Division,Metropolitan Division,Metropolitan Division,Metropolitan Division,Metropolitan Division,Metropolitan Division,Metropolitan Division,Metropolitan Division,Metropolitan Division,Metropolitan Division,Metropolitan Division,Metropolitan Division,Metropolitan Division,2018.0,NHL
10,Washington Capitals,82,49,26,7,105,.640,259,239,0.21,-0.04,.585,46,2018.0,NHL
11,Pittsburgh Penguins,82,47,29,6,100,.610,272,250,0.23,-0.04,.573,45,2018.0,NHL
12,Philadelphia Flyers,82,42,26,14,98,.598,251,243,0.07,-0.03,.543,40,2018.0,NHL
13,Columbus Blue Jackets,82,45,30,7,97,.591,242,230,0.11,-0.04,.537,39,2018.0,NHL
14,New Jersey Devils,82,44,29,9,97,.591,248,244,0.02,-0.03,.530,39,2018.0,NHL
15,Carolina Hurricanes,82,36,35,11,83,.506,228,256,-0.35,-0.01,.439,33,2018.0,NHL
16,New York Islanders,82,35,37,10,80,.488,264,296,-0.40,-0.01,.427,32,2018.0,NHL
17,New York Rangers,82,34,39,9,77,.470,231,268,-0.46,-0.01,.427,31,2018.0,NHL
18,Central Division,Central Division,Central Division,Central Division,Central Division,Central Division,Central Division,Central Division,Central Division,Central Division,Central Division,Central Division,Central Division,2018.0,NHL
19,Nashville Predators,82,53,18,11,117,.713,267,211,0.71,0.03,.652,47,2018.0,NHL
20,Winnipeg Jets,82,52,20,10,114,.695,277,218,0.74,0.02,.622,48,2018.0,NHL
21,Minnesota Wild,82,45,26,11,101,.616,253,232,0.29,0.04,.549,42,2018.0,NHL
22,Colorado Avalanche,82,43,30,9,95,.579,257,237,0.28,0.04,.518,41,2018.0,NHL
23,St. Louis Blues,82,44,32,6,94,.573,226,222,0.10,0.05,.518,41,2018.0,NHL
24,Dallas Stars,82,42,32,8,92,.561,235,225,0.17,0.04,.506,38,2018.0,NHL
25,Chicago Blackhawks,82,33,39,10,76,.463,229,256,-0.26,0.07,.409,32,2018.0,NHL
26,Pacific Division,Pacific Division,Pacific Division,Pacific Division,Pacific Division,Pacific Division,Pacific Division,Pacific Division,Pacific Division,Pacific Division,Pacific Division,Pacific Division,Pacific Division,2018.0,NHL
27,Vegas Golden Knights,82,51,24,7,109,.665,272,228,0.52,-0.01,.616,47,2018.0,NHL
28,Anaheim Ducks,82,44,25,13,101,.616,235,216,0.24,0.01,.555,40,2018.0,NHL
29,San Jose Sharks,82,45,27,10,100,.610,252,229,0.28,0.00,.537,40,2018.0,NHL
30,Los Angeles Kings,82,45,29,8,98,.598,239,203,0.44,0.00,.543,43,2018.0,NHL
31,Calgary Flames,82,37,35,10,84,.512,218,248,-0.33,0.03,.470,35,2018.0,NHL
32,Edmonton Oilers,82,36,40,6,78,.476,234,263,-0.32,0.03,.415,31,2018.0,NHL
33,Vancouver Canucks,82,31,40,11,73,.445,218,264,-0.51,0.05,.409,31,2018.0,NHL
34,Arizona Coyotes,82,29,41,12,70,.427,208,256,-0.53,0.05,.372,27,2018.0,NHL

In [2]:
nhl_df[(nhl_df['team']=='San Jose Sharks') & (nhl_df['year']==2018)]['W']

29    45
Name: W, dtype: object

In [3]:
cities['Population (2016 est.)[8]'][cities['NHL']=='Sharks']
cities.rename(columns={'Population (2016 est.)[8]':'Population'},inplace=True)

In [4]:
cities['NHL']=cities['NHL'].str.extract('([a-zA-Z\s]+)')
cities.dropna(subset=['NHL','Population'],inplace=True)
cities

,Metropolitan area,Population,NFL,MLB,NBA,NHL
0,New York City,20153634,GiantsJets[note 1],YankeesMets[note 2],KnicksNets,RangersIslandersDevils
1,Los Angeles,13310447,RamsChargers[note 4],DodgersAngels,LakersClippers,KingsDucks
2,San Francisco Bay Area,6657982,49ersRaiders[note 6],GiantsAthletics,Warriors,Sharks
3,Chicago,9512999,Bears[note 8],CubsWhite Sox,Bulls[note 9],Blackhawks
4,Dallas–Fort Worth,7233323,Cowboys,Rangers,Mavericks,Stars
5,"Washington, D.C.",6131977,Redskins,Nationals[note 10],Wizards[note 11],Capitals
6,Philadelphia,6070500,Eagles,Phillies[note 12],76ers,Flyers
7,Boston,4794447,Patriots[note 14],Red Sox[note 15],Celtics,Bruins
8,Minneapolis–Saint Paul,3551036,Vikings,Twins,Timberwolves,Wild
9,Denver,2853077,Broncos,Rockies,Nuggets[note 17],Avalanche
10,Miami–Fort Lauderdale,6066387,Dolphins,Marlins,Heat,Panthers
11,Phoenix,4661537,Cardinals,Diamondbacks,Suns,Coyotes
12,Detroit,4297617,Lions,Tigers[note 20],Pistons[note 21],Red Wings
13,Toronto,5928040,— [note 22],Blue Jays,Raptors[note 23],Maple Leafs
16,Tampa Bay Area,3032171,Buccaneers,Rays,—,Lightning
17,Pittsburgh,2342299,Steelers,Pirates,[note 27],Penguins
22,St. Louis,2807002,[note 40],Cardinals[note 41],[note 42],Blues
26,Nashville,1865298,Titans,—,—,Predators
29,Buffalo,1132804,Bills[note 56],[note 57],[note 58],Sabres
30,Montreal,4098927,—,[note 59],—,Canadiens
31,Vancouver,2463431,—,—,[note 60],Canucks
34,Columbus,2041520,—,—,—,Blue Jackets
35,Calgary,1392609,—,—,—,Flames
36,Ottawa,1323783,—,—,—,Senators
37,Edmonton,1321426,—,—,—,Oilers
39,Winnipeg,778489,—,—,—,Jets
43,Las Vegas,2155664,[note 6],—,—,Golden Knights
47,Raleigh,1302946,—,—,—,Hurricanes

In [5]:
cities['NHL'][cities['NHL']=='RangersIslandersDevils']='Rangers Islanders Devils'
cities['NHL']

0     Rangers Islanders Devils
1                   KingsDucks
2                       Sharks
3                   Blackhawks
4                        Stars
5                     Capitals
6                       Flyers
7                       Bruins
8                         Wild
9                    Avalanche
10                    Panthers
11                     Coyotes
12                   Red Wings
13                 Maple Leafs
16                   Lightning
17                    Penguins
22                       Blues
26                   Predators
29                      Sabres
30                   Canadiens
31                     Canucks
34                Blue Jackets
35                      Flames
36                    Senators
37                      Oilers
39                        Jets
43              Golden Knights
47                  Hurricanes
Name: NHL, dtype: object

In [6]:
cities['NHL'][cities['NHL']=='KingsDucks']='Kings Ducks'
cities['NHL']

0     Rangers Islanders Devils
1                  Kings Ducks
2                       Sharks
3                   Blackhawks
4                        Stars
5                     Capitals
6                       Flyers
7                       Bruins
8                         Wild
9                    Avalanche
10                    Panthers
11                     Coyotes
12                   Red Wings
13                 Maple Leafs
16                   Lightning
17                    Penguins
22                       Blues
26                   Predators
29                      Sabres
30                   Canadiens
31                     Canucks
34                Blue Jackets
35                      Flames
36                    Senators
37                      Oilers
39                        Jets
43              Golden Knights
47                  Hurricanes
Name: NHL, dtype: object

In [7]:
nhl_df2=nhl_df2[1:]
nhl_df2['W']

1                        54
2                        50
3                        49
4                        44
5                        30
6                        29
7                        28
8                        25
9     Metropolitan Division
10                       49
11                       47
12                       42
13                       45
14                       44
15                       36
16                       35
17                       34
18         Central Division
19                       53
20                       52
21                       45
22                       43
23                       44
24                       42
25                       33
26         Pacific Division
27                       51
28                       44
29                       45
30                       45
31                       37
32                       36
33                       31
34                       29
Name: W, dtype: object

In [8]:
nhl_df2['W']=nhl_df2['W'].str.extract('([0-9]+)')
nhl_df2['W']

1      54
2      50
3      49
4      44
5      30
6      29
7      28
8      25
9     NaN
10     49
11     47
12     42
13     45
14     44
15     36
16     35
17     34
18    NaN
19     53
20     52
21     45
22     43
23     44
24     42
25     33
26    NaN
27     51
28     44
29     45
30     45
31     37
32     36
33     31
34     29
Name: W, dtype: object

In [9]:
#nhl_df2['W']=nhl_df2['W'].dropna()

In [10]:
#nhl_df2['W'].dropna(inplace=True)

In [11]:
#nhl_df2['W']

In [12]:
nhl_df2['W'][nhl_df2['team']=='San Jose Sharks'].astype(float)

29    45.0
Name: W, dtype: float64

In [13]:
# def WL_ratio(x):
#     return float(nhl_df['W'][nhl_df['team']==x])/float(nhl_df['W'][nhl_df['team']==x]+nhl_df['L'][nhl_df['team']==x])
# WL_ratio('San Jose Sharks')

In [14]:
nhl_df2['L']=nhl_df2['L'].str.extract('([0-9]+)')
nhl_df2['L']=nhl_df2['L'].astype(float)

In [15]:
nhl_df2.dropna(subset=['L','W'],inplace=True)
nhl_df2['L']

1     23.0
2     20.0
3     26.0
4     30.0
5     39.0
6     40.0
7     43.0
8     45.0
10    26.0
11    29.0
12    26.0
13    30.0
14    29.0
15    35.0
16    37.0
17    39.0
19    18.0
20    20.0
21    26.0
22    30.0
23    32.0
24    32.0
25    39.0
27    24.0
28    25.0
29    27.0
30    29.0
31    35.0
32    40.0
33    40.0
34    41.0
Name: L, dtype: float64

In [16]:
nhl_df2

,team,GP,W,L,OL,PTS,PTS%,GF,GA,SRS,SOS,RPt%,ROW,year,League
1,Tampa Bay Lightning,82,54,23.0,5,113,.689,296,236,0.66,-0.07,.634,48,2018.0,NHL
2,Boston Bruins,82,50,20.0,12,112,.683,270,214,0.62,-0.07,.610,47,2018.0,NHL
3,Toronto Maple Leafs,82,49,26.0,7,105,.640,277,232,0.49,-0.06,.567,42,2018.0,NHL
4,Florida Panthers,82,44,30.0,8,96,.585,248,246,-0.01,-0.04,.537,41,2018.0,NHL
5,Detroit Red Wings,82,30,39.0,13,73,.445,217,255,-0.48,-0.01,.341,25,2018.0,NHL
6,Montreal Canadiens,82,29,40.0,13,71,.433,209,264,-0.68,0.00,.378,27,2018.0,NHL
7,Ottawa Senators,82,28,43.0,11,67,.409,221,291,-0.85,0.00,.372,26,2018.0,NHL
8,Buffalo Sabres,82,25,45.0,12,62,.378,199,280,-0.98,0.01,.311,24,2018.0,NHL
10,Washington Capitals,82,49,26.0,7,105,.640,259,239,0.21,-0.04,.585,46,2018.0,NHL
11,Pittsburgh Penguins,82,47,29.0,6,100,.610,272,250,0.23,-0.04,.573,45,2018.0,NHL
12,Philadelphia Flyers,82,42,26.0,14,98,.598,251,243,0.07,-0.03,.543,40,2018.0,NHL
13,Columbus Blue Jackets,82,45,30.0,7,97,.591,242,230,0.11,-0.04,.537,39,2018.0,NHL
14,New Jersey Devils,82,44,29.0,9,97,.591,248,244,0.02,-0.03,.530,39,2018.0,NHL
15,Carolina Hurricanes,82,36,35.0,11,83,.506,228,256,-0.35,-0.01,.439,33,2018.0,NHL
16,New York Islanders,82,35,37.0,10,80,.488,264,296,-0.40,-0.01,.427,32,2018.0,NHL
17,New York Rangers,82,34,39.0,9,77,.470,231,268,-0.46,-0.01,.427,31,2018.0,NHL
19,Nashville Predators,82,53,18.0,11,117,.713,267,211,0.71,0.03,.652,47,2018.0,NHL
20,Winnipeg Jets,82,52,20.0,10,114,.695,277,218,0.74,0.02,.622,48,2018.0,NHL
21,Minnesota Wild,82,45,26.0,11,101,.616,253,232,0.29,0.04,.549,42,2018.0,NHL
22,Colorado Avalanche,82,43,30.0,9,95,.579,257,237,0.28,0.04,.518,41,2018.0,NHL
23,St. Louis Blues,82,44,32.0,6,94,.573,226,222,0.10,0.05,.518,41,2018.0,NHL
24,Dallas Stars,82,42,32.0,8,92,.561,235,225,0.17,0.04,.506,38,2018.0,NHL
25,Chicago Blackhawks,82,33,39.0,10,76,.463,229,256,-0.26,0.07,.409,32,2018.0,NHL
27,Vegas Golden Knights,82,51,24.0,7,109,.665,272,228,0.52,-0.01,.616,47,2018.0,NHL
28,Anaheim Ducks,82,44,25.0,13,101,.616,235,216,0.24,0.01,.555,40,2018.0,NHL
29,San Jose Sharks,82,45,27.0,10,100,.610,252,229,0.28,0.00,.537,40,2018.0,NHL
30,Los Angeles Kings,82,45,29.0,8,98,.598,239,203,0.44,0.00,.543,43,2018.0,NHL
31,Calgary Flames,82,37,35.0,10,84,.512,218,248,-0.33,0.03,.470,35,2018.0,NHL
32,Edmonton Oilers,82,36,40.0,6,78,.476,234,263,-0.32,0.03,.415,31,2018.0,NHL
33,Vancouver Canucks,82,31,40.0,11,73,.445,218,264,-0.51,0.05,.409,31,2018.0,NHL
34,Arizona Coyotes,82,29,41.0,12,70,.427,208,256,-0.53,0.05,.372,27,2018.0,NHL

In [17]:
cnt=0
cnt1=0
cities['ratio']=0
for y in cities['NHL']:
    Win=0
    Loss=0
    for r in y.split():
        print (r)
        if len(y)>0:
            n=cities.loc[cities['NHL']==y].index.values
        for x in nhl_df2['team']:
            m=nhl_df2.loc[nhl_df2['team']==x].index.values
            if r in x and len(y)>0:
            #print("y:{}, x:{}".format(y,x))
                Win=Win+float(nhl_df2.loc[m,'W'].values[0])
                Loss=Loss+float(nhl_df2.loc[m,'L'].values[0])
                ratio=Win/(Win+Loss)
                cities.loc[n,'ratio']=ratio
                break

#correlation=nhl_df2['ratio'].corr(cities['Population'])
cities['Population']=cities['Population'].astype(float)
cities['Population'].corr(cities['ratio'])

Rangers
Islanders
Devils
Kings
Ducks
Sharks
Blackhawks
Stars
Capitals
Flyers
Bruins
Wild
Avalanche
Panthers
Coyotes
Red
Wings
Maple
Leafs
Lightning
Penguins
Blues
Predators
Sabres
Canadiens
Canucks
Blue
Jackets
Flames
Senators
Oilers
Jets
Golden
Knights
Hurricanes

0.012308996455744264

In [18]:
cities['Population']

0     20153634.0
1     13310447.0
2      6657982.0
3      9512999.0
4      7233323.0
5      6131977.0
6      6070500.0
7      4794447.0
8      3551036.0
9      2853077.0
10     6066387.0
11     4661537.0
12     4297617.0
13     5928040.0
16     3032171.0
17     2342299.0
22     2807002.0
26     1865298.0
29     1132804.0
30     4098927.0
31     2463431.0
34     2041520.0
35     1392609.0
36     1323783.0
37     1321426.0
39      778489.0
43     2155664.0
47     1302946.0
Name: Population, dtype: float64

In [19]:
import pandas as pd
import numpy as np
import scipy.stats as stats
import re

nhl_df=pd.read_csv("nhl.csv")
cities=pd.read_html("wikipedia_data.html")[1]
cities=cities.iloc[:-1,[0,3,5,6,7,8]]

def nhl_correlation(): 
    cities['NHL']=cities['NHL'].str.extract('([a-zA-Z0-9 \.]*)')
    nhl_df['team']=nhl_df['team'].str.extract('([a-zA-Z0-9 \.]*)')
    nhl_df2=nhl_df[nhl_df['year']==2018]
    cities.rename(columns={'Population (2016 est.)[8]':'Population'},inplace=True)
    cities['NHL'][cities['NHL']=='RangersIslandersDevils']='Rangers'
    cities['NHL'][cities['NHL']=='Rangers']='Rangers Islanders Devils'
    cities['NHL'][cities['NHL']=='KingsDucks']='Kings'
    cities['NHL'][cities['NHL']=='Kings']='Kings Ducks'
    cities['NHL']=cities['NHL'].str.extract('([a-zA-Z\s]+)')
    cities.dropna(subset=['NHL','Population'],inplace=True)
    nhl_df2=nhl_df2[1:]
    nhl_df2['W']=nhl_df2['W'].str.extract('([0-9]+)')
    nhl_df2['L']=nhl_df2['L'].str.extract('([0-9]+)')
    nhl_df2['L']=nhl_df2['L'].astype(float)
    nhl_df2.dropna(subset=['L','W'],inplace=True)
    cities['ratio']=0
    for y in cities['NHL']:
        Win=0
        Loss=0
        for r in y.split():
            n=cities.loc[cities['NHL']==y].index.values
            for x in nhl_df2['team']:
                 m=nhl_df2.loc[nhl_df2['team']==x].index.values
                 if r in x and len(y)>0:
            #print("y:{}, x:{}".format(y,x))
                    Win=Win+float(nhl_df2.loc[m,'W'].values[0])
                    Loss=Loss+float(nhl_df2.loc[m,'L'].values[0])
                    ratio=Win/(Win+Loss)
                    cities.loc[n,'ratio']=ratio
                    break
    cities['Population']=cities['Population'].astype(float)
    
    population_by_region = list(cities['Population']) # pass in metropolitan area population from cities
    win_loss_by_region = list(cities['ratio']) # pass in win/loss ratio from nhl_df in the same order as cities["Metropolitan area"]

    assert len(population_by_region) == len(win_loss_by_region), "Q1: Your lists must be the same length"
    assert len(population_by_region) == 28, "Q1: There should be 28 teams being analysed for NHL"
    
    return cities['Population'].corr(cities['ratio'])
nhl_correlation()

0.012308996455744264

## Question 2
For this question, calculate the win/loss ratio's correlation with the population of the city it is in for the **NBA** using **2018** data.

In [20]:
cities=pd.read_html("wikipedia_data.html")[1]
cities2=cities

cities2

,Metropolitan area,Country,Pop.rank,Population (2016 est.)[8],B4,NFL,MLB,NBA,NHL,B6,MLS,CFL
0,New York City,United States,1,20153634,9,GiantsJets[note 1],YankeesMets[note 2],KnicksNets,RangersIslandersDevils[note 3],11,Red BullsNew York City FC,—
1,Los Angeles,United States,2,13310447,8,RamsChargers[note 4],DodgersAngels,LakersClippers,KingsDucks,10,GalaxyLos Angeles FC[note 5],—
2,San Francisco Bay Area,United States,6,6657982,6,49ersRaiders[note 6],GiantsAthletics,Warriors,Sharks[note 7],7,Earthquakes,—
3,Chicago,United States,3,9512999,5,Bears[note 8],CubsWhite Sox,Bulls[note 9],Blackhawks,6,Fire,—
4,Dallas–Fort Worth,United States,4,7233323,4,Cowboys,Rangers,Mavericks,Stars,5,FC Dallas,—
5,"Washington, D.C.",United States,7,6131977,4,Redskins,Nationals[note 10],Wizards[note 11],Capitals,5,D.C. United,—
6,Philadelphia,United States,8,6070500,4,Eagles,Phillies[note 12],76ers,Flyers[note 13],5,Union,—
7,Boston,United States,12,4794447,4,Patriots[note 14],Red Sox[note 15],Celtics,Bruins,5,Revolution,—
8,Minneapolis–Saint Paul,United States,17,3551036,4,Vikings,Twins,Timberwolves,Wild[note 16],5,United FC,—
9,Denver,United States,20,2853077,4,Broncos,Rockies,Nuggets[note 17],Avalanche[note 18],5,Rapids,—
10,Miami–Fort Lauderdale,United States,9,6066387,4,Dolphins,Marlins,Heat,Panthers,4,[note 19],—
11,Phoenix,United States,13,4661537,4,Cardinals,Diamondbacks,Suns,Coyotes,4,—,—
12,Detroit,United States,14,4297617,4,Lions,Tigers[note 20],Pistons[note 21],Red Wings,4,—,—
13,Toronto,Canada,10,5928040,3,— [note 22],Blue Jays,Raptors[note 23],Maple Leafs,5,Toronto FC,Argonauts
14,Houston,United States,5,6772470,3,Texans[note 24],Astros,Rockets,—,4,Dynamo,—
15,Atlanta,United States,11,5789700,3,Falcons,Braves,Hawks,[note 25],4,United FC,—
16,Tampa Bay Area,United States,19,3032171,3,Buccaneers,Rays,—,Lightning,3,[note 26],—
17,Pittsburgh,United States,28,2342299,3,Steelers,Pirates,[note 27],Penguins[note 28],3,—,—
18,Cleveland,United States,33,2055612,3,Browns[note 29],Indians[note 30],Cavaliers[note 31],[note 32],3,—,—
19,Seattle,United States,16,3798902,2,Seahawks,Mariners,[note 33],[note 34],3,Sounders FC,—
20,Cincinnati,United States,30,2165139,2,Bengals,Reds[note 35],[note 36],—,3,FC Cincinnati,—
21,Kansas City,United States,32,2104509,2,Chiefs,Royals[note 37],[note 38],[note 39],3,Sporting Kansas City,—
22,St. Louis,United States,21,2807002,2,[note 40],Cardinals[note 41],[note 42],Blues[note 43],2,[note 44],—
23,Baltimore,United States,22,2798886,2,Ravens[note 45],Orioles[note 46],[note 47],—,2,—,[note 48]
24,Charlotte,United States,23,2474314,2,Panthers,—,Hornets[note 49],—,2,—,—
25,Indianapolis,United States,35,2004230,2,Colts,[note 50],Pacers[note 51],—,2,—,—
26,Nashville,United States,36,1865298,2,Titans,—,—,Predators,2,[note 52],—
27,Milwaukee,United States,37,1572482,2,[note 53],Brewers[note 54],Bucks,—,2,—,—
28,New Orleans,United States,45,1268883,2,Saints,—,Pelicans[note 55],—,2,—,—
29,Buffalo,United States,47,1132804,2,Bills[note 56],[note 57],[note 58],Sabres,2,—,—
30,Montreal,Canada,15,4098927,1,—,[note 59],—,Canadiens,3,Impact,Alouettes
31,Vancouver,Canada,24,2463431,1,—,—,[note 60],Canucks,3,Whitecaps FC,Lions
32,Orlando,United States,25,2441257,1,—,—,Magic,—,2,Orlando City SC,—
33,Portland,United States,27,2424955,1,—,—,Trail Blazers,—,2,Timbers,—
34,Columbus,United States,34,2041520,1,—,—,—,Blue Jackets,2,Crew SC,—
35,Calgary,Canada,39,1392609,1,—,—,—,Flames,2,—,Stampeders
36,Ottawa,Canada,42,1323783,1,—,—,—,Senators,2,—,Redblacks
37,Edmonton,Canada,43,1321426,1,—,—,—,Oilers,2,—,Eskimos
38,Salt Lake City,United States,46,1186187,1,—,—,Jazz,—,2,Real Salt Lake,—
39,Winnipeg,Canada,67,778489,1,—,—,—,Jets[note 61],2,—,Blue Bombers
40,San Diego,United States,18,3317749,1,[note 62],Padres,[note 63],—,1,—,—
41,San Antonio,United States,26,2429609,1,[note 64],—,Spurs,—,1,—,[note 65]
42,Sacramento,United States,29,2296418,1,—,—,Kings,—,1,—,[note 66]
43,Las Vegas,United States,31,2155664,1,[note 6],—,—,Golden Knights,1,—,[note 67]
44,Jacksonville,United States,38,1478212,1,Jaguars,—,—,—,1,—,—
45,Oklahoma City,United States,40,1373211,1,—,—,Thunder[note 68],—,1,—,—
46,Memphis,United States,41,1342842,1,[note 69],—,Grizzlies,—,1,—,[note 70]
47,Raleigh,United States,44,1302946,1,—,—,—,Hurricanes,1,—,—
48,Green Bay,United States,—,318236,1,Packers,—,—,—,1,—,—
49,Hamilton,Canada,—,747545,0,—,—,—,[note 71],1,—,Tiger-Cats
50,Regina,Canada,—,236481,0,—,—,—,—,1,—,Roughriders
51,Totals,—,—,–,123,32,30,30,31,156,24[note 72],9

In [21]:
cities2['NBA']=cities['NBA'].str.replace('\[.*\]','',regex=True)
cities2

,Metropolitan area,Country,Pop.rank,Population (2016 est.)[8],B4,NFL,MLB,NBA,NHL,B6,MLS,CFL
0,New York City,United States,1,20153634,9,GiantsJets[note 1],YankeesMets[note 2],KnicksNets,RangersIslandersDevils[note 3],11,Red BullsNew York City FC,—
1,Los Angeles,United States,2,13310447,8,RamsChargers[note 4],DodgersAngels,LakersClippers,KingsDucks,10,GalaxyLos Angeles FC[note 5],—
2,San Francisco Bay Area,United States,6,6657982,6,49ersRaiders[note 6],GiantsAthletics,Warriors,Sharks[note 7],7,Earthquakes,—
3,Chicago,United States,3,9512999,5,Bears[note 8],CubsWhite Sox,Bulls,Blackhawks,6,Fire,—
4,Dallas–Fort Worth,United States,4,7233323,4,Cowboys,Rangers,Mavericks,Stars,5,FC Dallas,—
5,"Washington, D.C.",United States,7,6131977,4,Redskins,Nationals[note 10],Wizards,Capitals,5,D.C. United,—
6,Philadelphia,United States,8,6070500,4,Eagles,Phillies[note 12],76ers,Flyers[note 13],5,Union,—
7,Boston,United States,12,4794447,4,Patriots[note 14],Red Sox[note 15],Celtics,Bruins,5,Revolution,—
8,Minneapolis–Saint Paul,United States,17,3551036,4,Vikings,Twins,Timberwolves,Wild[note 16],5,United FC,—
9,Denver,United States,20,2853077,4,Broncos,Rockies,Nuggets,Avalanche[note 18],5,Rapids,—
10,Miami–Fort Lauderdale,United States,9,6066387,4,Dolphins,Marlins,Heat,Panthers,4,[note 19],—
11,Phoenix,United States,13,4661537,4,Cardinals,Diamondbacks,Suns,Coyotes,4,—,—
12,Detroit,United States,14,4297617,4,Lions,Tigers[note 20],Pistons,Red Wings,4,—,—
13,Toronto,Canada,10,5928040,3,— [note 22],Blue Jays,Raptors,Maple Leafs,5,Toronto FC,Argonauts
14,Houston,United States,5,6772470,3,Texans[note 24],Astros,Rockets,—,4,Dynamo,—
15,Atlanta,United States,11,5789700,3,Falcons,Braves,Hawks,[note 25],4,United FC,—
16,Tampa Bay Area,United States,19,3032171,3,Buccaneers,Rays,—,Lightning,3,[note 26],—
17,Pittsburgh,United States,28,2342299,3,Steelers,Pirates,,Penguins[note 28],3,—,—
18,Cleveland,United States,33,2055612,3,Browns[note 29],Indians[note 30],Cavaliers,[note 32],3,—,—
19,Seattle,United States,16,3798902,2,Seahawks,Mariners,,[note 34],3,Sounders FC,—
20,Cincinnati,United States,30,2165139,2,Bengals,Reds[note 35],,—,3,FC Cincinnati,—
21,Kansas City,United States,32,2104509,2,Chiefs,Royals[note 37],,[note 39],3,Sporting Kansas City,—
22,St. Louis,United States,21,2807002,2,[note 40],Cardinals[note 41],,Blues[note 43],2,[note 44],—
23,Baltimore,United States,22,2798886,2,Ravens[note 45],Orioles[note 46],,—,2,—,[note 48]
24,Charlotte,United States,23,2474314,2,Panthers,—,Hornets,—,2,—,—
25,Indianapolis,United States,35,2004230,2,Colts,[note 50],Pacers,—,2,—,—
26,Nashville,United States,36,1865298,2,Titans,—,—,Predators,2,[note 52],—
27,Milwaukee,United States,37,1572482,2,[note 53],Brewers[note 54],Bucks,—,2,—,—
28,New Orleans,United States,45,1268883,2,Saints,—,Pelicans,—,2,—,—
29,Buffalo,United States,47,1132804,2,Bills[note 56],[note 57],,Sabres,2,—,—
30,Montreal,Canada,15,4098927,1,—,[note 59],—,Canadiens,3,Impact,Alouettes
31,Vancouver,Canada,24,2463431,1,—,—,,Canucks,3,Whitecaps FC,Lions
32,Orlando,United States,25,2441257,1,—,—,Magic,—,2,Orlando City SC,—
33,Portland,United States,27,2424955,1,—,—,Trail Blazers,—,2,Timbers,—
34,Columbus,United States,34,2041520,1,—,—,—,Blue Jackets,2,Crew SC,—
35,Calgary,Canada,39,1392609,1,—,—,—,Flames,2,—,Stampeders
36,Ottawa,Canada,42,1323783,1,—,—,—,Senators,2,—,Redblacks
37,Edmonton,Canada,43,1321426,1,—,—,—,Oilers,2,—,Eskimos
38,Salt Lake City,United States,46,1186187,1,—,—,Jazz,—,2,Real Salt Lake,—
39,Winnipeg,Canada,67,778489,1,—,—,—,Jets[note 61],2,—,Blue Bombers
40,San Diego,United States,18,3317749,1,[note 62],Padres,,—,1,—,—
41,San Antonio,United States,26,2429609,1,[note 64],—,Spurs,—,1,—,[note 65]
42,Sacramento,United States,29,2296418,1,—,—,Kings,—,1,—,[note 66]
43,Las Vegas,United States,31,2155664,1,[note 6],—,—,Golden Knights,1,—,[note 67]
44,Jacksonville,United States,38,1478212,1,Jaguars,—,—,—,1,—,—
45,Oklahoma City,United States,40,1373211,1,—,—,Thunder,—,1,—,—
46,Memphis,United States,41,1342842,1,[note 69],—,Grizzlies,—,1,—,[note 70]
47,Raleigh,United States,44,1302946,1,—,—,—,Hurricanes,1,—,—
48,Green Bay,United States,—,318236,1,Packers,—,—,—,1,—,—
49,Hamilton,Canada,—,747545,0,—,—,—,[note 71],1,—,Tiger-Cats
50,Regina,Canada,—,236481,0,—,—,—,—,1,—,Roughriders
51,Totals,—,—,–,123,32,30,30,31,156,24[note 72],9

In [22]:
cities2

,Metropolitan area,Country,Pop.rank,Population (2016 est.)[8],B4,NFL,MLB,NBA,NHL,B6,MLS,CFL
0,New York City,United States,1,20153634,9,GiantsJets[note 1],YankeesMets[note 2],KnicksNets,RangersIslandersDevils[note 3],11,Red BullsNew York City FC,—
1,Los Angeles,United States,2,13310447,8,RamsChargers[note 4],DodgersAngels,LakersClippers,KingsDucks,10,GalaxyLos Angeles FC[note 5],—
2,San Francisco Bay Area,United States,6,6657982,6,49ersRaiders[note 6],GiantsAthletics,Warriors,Sharks[note 7],7,Earthquakes,—
3,Chicago,United States,3,9512999,5,Bears[note 8],CubsWhite Sox,Bulls,Blackhawks,6,Fire,—
4,Dallas–Fort Worth,United States,4,7233323,4,Cowboys,Rangers,Mavericks,Stars,5,FC Dallas,—
5,"Washington, D.C.",United States,7,6131977,4,Redskins,Nationals[note 10],Wizards,Capitals,5,D.C. United,—
6,Philadelphia,United States,8,6070500,4,Eagles,Phillies[note 12],76ers,Flyers[note 13],5,Union,—
7,Boston,United States,12,4794447,4,Patriots[note 14],Red Sox[note 15],Celtics,Bruins,5,Revolution,—
8,Minneapolis–Saint Paul,United States,17,3551036,4,Vikings,Twins,Timberwolves,Wild[note 16],5,United FC,—
9,Denver,United States,20,2853077,4,Broncos,Rockies,Nuggets,Avalanche[note 18],5,Rapids,—
10,Miami–Fort Lauderdale,United States,9,6066387,4,Dolphins,Marlins,Heat,Panthers,4,[note 19],—
11,Phoenix,United States,13,4661537,4,Cardinals,Diamondbacks,Suns,Coyotes,4,—,—
12,Detroit,United States,14,4297617,4,Lions,Tigers[note 20],Pistons,Red Wings,4,—,—
13,Toronto,Canada,10,5928040,3,— [note 22],Blue Jays,Raptors,Maple Leafs,5,Toronto FC,Argonauts
14,Houston,United States,5,6772470,3,Texans[note 24],Astros,Rockets,—,4,Dynamo,—
15,Atlanta,United States,11,5789700,3,Falcons,Braves,Hawks,[note 25],4,United FC,—
16,Tampa Bay Area,United States,19,3032171,3,Buccaneers,Rays,—,Lightning,3,[note 26],—
17,Pittsburgh,United States,28,2342299,3,Steelers,Pirates,,Penguins[note 28],3,—,—
18,Cleveland,United States,33,2055612,3,Browns[note 29],Indians[note 30],Cavaliers,[note 32],3,—,—
19,Seattle,United States,16,3798902,2,Seahawks,Mariners,,[note 34],3,Sounders FC,—
20,Cincinnati,United States,30,2165139,2,Bengals,Reds[note 35],,—,3,FC Cincinnati,—
21,Kansas City,United States,32,2104509,2,Chiefs,Royals[note 37],,[note 39],3,Sporting Kansas City,—
22,St. Louis,United States,21,2807002,2,[note 40],Cardinals[note 41],,Blues[note 43],2,[note 44],—
23,Baltimore,United States,22,2798886,2,Ravens[note 45],Orioles[note 46],,—,2,—,[note 48]
24,Charlotte,United States,23,2474314,2,Panthers,—,Hornets,—,2,—,—
25,Indianapolis,United States,35,2004230,2,Colts,[note 50],Pacers,—,2,—,—
26,Nashville,United States,36,1865298,2,Titans,—,—,Predators,2,[note 52],—
27,Milwaukee,United States,37,1572482,2,[note 53],Brewers[note 54],Bucks,—,2,—,—
28,New Orleans,United States,45,1268883,2,Saints,—,Pelicans,—,2,—,—
29,Buffalo,United States,47,1132804,2,Bills[note 56],[note 57],,Sabres,2,—,—
30,Montreal,Canada,15,4098927,1,—,[note 59],—,Canadiens,3,Impact,Alouettes
31,Vancouver,Canada,24,2463431,1,—,—,,Canucks,3,Whitecaps FC,Lions
32,Orlando,United States,25,2441257,1,—,—,Magic,—,2,Orlando City SC,—
33,Portland,United States,27,2424955,1,—,—,Trail Blazers,—,2,Timbers,—
34,Columbus,United States,34,2041520,1,—,—,—,Blue Jackets,2,Crew SC,—
35,Calgary,Canada,39,1392609,1,—,—,—,Flames,2,—,Stampeders
36,Ottawa,Canada,42,1323783,1,—,—,—,Senators,2,—,Redblacks
37,Edmonton,Canada,43,1321426,1,—,—,—,Oilers,2,—,Eskimos
38,Salt Lake City,United States,46,1186187,1,—,—,Jazz,—,2,Real Salt Lake,—
39,Winnipeg,Canada,67,778489,1,—,—,—,Jets[note 61],2,—,Blue Bombers
40,San Diego,United States,18,3317749,1,[note 62],Padres,,—,1,—,—
41,San Antonio,United States,26,2429609,1,[note 64],—,Spurs,—,1,—,[note 65]
42,Sacramento,United States,29,2296418,1,—,—,Kings,—,1,—,[note 66]
43,Las Vegas,United States,31,2155664,1,[note 6],—,—,Golden Knights,1,—,[note 67]
44,Jacksonville,United States,38,1478212,1,Jaguars,—,—,—,1,—,—
45,Oklahoma City,United States,40,1373211,1,—,—,Thunder,—,1,—,—
46,Memphis,United States,41,1342842,1,[note 69],—,Grizzlies,—,1,—,[note 70]
47,Raleigh,United States,44,1302946,1,—,—,—,Hurricanes,1,—,—
48,Green Bay,United States,—,318236,1,Packers,—,—,—,1,—,—
49,Hamilton,Canada,—,747545,0,—,—,—,[note 71],1,—,Tiger-Cats
50,Regina,Canada,—,236481,0,—,—,—,—,1,—,Roughriders
51,Totals,—,—,–,123,32,30,30,31,156,24[note 72],9

In [23]:
cities2['NBA']=cities2['NBA'].str.extract('([A-Za-z0-9\s]+)')
cities2['NBA'][cities2['NBA']=='KnicksNets']='Knicks Nets'
cities2['NBA'][cities2['NBA']=='LakersClippers']='Lakers Clippers'
cities2.dropna(subset=['NBA','Population (2016 est.)[8]'],inplace=True)
cities2

,Metropolitan area,Country,Pop.rank,Population (2016 est.)[8],B4,NFL,MLB,NBA,NHL,B6,MLS,CFL
0,New York City,United States,1,20153634,9,GiantsJets[note 1],YankeesMets[note 2],Knicks Nets,RangersIslandersDevils[note 3],11,Red BullsNew York City FC,—
1,Los Angeles,United States,2,13310447,8,RamsChargers[note 4],DodgersAngels,Lakers Clippers,KingsDucks,10,GalaxyLos Angeles FC[note 5],—
2,San Francisco Bay Area,United States,6,6657982,6,49ersRaiders[note 6],GiantsAthletics,Warriors,Sharks[note 7],7,Earthquakes,—
3,Chicago,United States,3,9512999,5,Bears[note 8],CubsWhite Sox,Bulls,Blackhawks,6,Fire,—
4,Dallas–Fort Worth,United States,4,7233323,4,Cowboys,Rangers,Mavericks,Stars,5,FC Dallas,—
5,"Washington, D.C.",United States,7,6131977,4,Redskins,Nationals[note 10],Wizards,Capitals,5,D.C. United,—
6,Philadelphia,United States,8,6070500,4,Eagles,Phillies[note 12],76ers,Flyers[note 13],5,Union,—
7,Boston,United States,12,4794447,4,Patriots[note 14],Red Sox[note 15],Celtics,Bruins,5,Revolution,—
8,Minneapolis–Saint Paul,United States,17,3551036,4,Vikings,Twins,Timberwolves,Wild[note 16],5,United FC,—
9,Denver,United States,20,2853077,4,Broncos,Rockies,Nuggets,Avalanche[note 18],5,Rapids,—
10,Miami–Fort Lauderdale,United States,9,6066387,4,Dolphins,Marlins,Heat,Panthers,4,[note 19],—
11,Phoenix,United States,13,4661537,4,Cardinals,Diamondbacks,Suns,Coyotes,4,—,—
12,Detroit,United States,14,4297617,4,Lions,Tigers[note 20],Pistons,Red Wings,4,—,—
13,Toronto,Canada,10,5928040,3,— [note 22],Blue Jays,Raptors,Maple Leafs,5,Toronto FC,Argonauts
14,Houston,United States,5,6772470,3,Texans[note 24],Astros,Rockets,—,4,Dynamo,—
15,Atlanta,United States,11,5789700,3,Falcons,Braves,Hawks,[note 25],4,United FC,—
18,Cleveland,United States,33,2055612,3,Browns[note 29],Indians[note 30],Cavaliers,[note 32],3,—,—
24,Charlotte,United States,23,2474314,2,Panthers,—,Hornets,—,2,—,—
25,Indianapolis,United States,35,2004230,2,Colts,[note 50],Pacers,—,2,—,—
27,Milwaukee,United States,37,1572482,2,[note 53],Brewers[note 54],Bucks,—,2,—,—
28,New Orleans,United States,45,1268883,2,Saints,—,Pelicans,—,2,—,—
32,Orlando,United States,25,2441257,1,—,—,Magic,—,2,Orlando City SC,—
33,Portland,United States,27,2424955,1,—,—,Trail Blazers,—,2,Timbers,—
38,Salt Lake City,United States,46,1186187,1,—,—,Jazz,—,2,Real Salt Lake,—
41,San Antonio,United States,26,2429609,1,[note 64],—,Spurs,—,1,—,[note 65]
42,Sacramento,United States,29,2296418,1,—,—,Kings,—,1,—,[note 66]
45,Oklahoma City,United States,40,1373211,1,—,—,Thunder,—,1,—,—
46,Memphis,United States,41,1342842,1,[note 69],—,Grizzlies,—,1,—,[note 70]
51,Totals,—,—,–,123,32,30,30,31,156,24[note 72],9

In [24]:
nba_df=pd.read_csv("nba.csv")
nba_df2=nba_df
nba_df2['team']=nba_df['team'].str.extract('([a-zA-Z\s]+)')
nba_df2=nba_df2[nba_df2['year']==2018]

In [25]:
nba_df2['team'][nba_df2['team']=='Philadelphia ']='Philadelphia 76ers'
nba_df2

,team,W,L,W/L%,GB,PS/G,PA/G,SRS,year,League
0,Toronto Raptors,59,23,0.72,—,111.7,103.9,7.29,2018,NBA
1,Boston Celtics,55,27,0.6709999999999999,4.0,104.0,100.4,3.23,2018,NBA
2,Philadelphia 76ers,52,30,0.634,7.0,109.8,105.3,4.3,2018,NBA
3,Cleveland Cavaliers,50,32,0.61,9.0,110.9,109.9,0.59,2018,NBA
4,Indiana Pacers,48,34,0.585,11.0,105.6,104.2,1.18,2018,NBA
5,Miami Heat,44,38,0.537,15.0,103.4,102.9,0.15,2018,NBA
6,Milwaukee Bucks,44,38,0.537,15.0,106.5,106.8,-0.45,2018,NBA
7,Washington Wizards,43,39,0.524,16.0,106.6,106.0,0.53,2018,NBA
8,Detroit Pistons,39,43,0.47600000000000003,20.0,103.8,103.9,-0.26,2018,NBA
9,Charlotte Hornets,36,46,0.439,23.0,108.2,108.0,0.07,2018,NBA
10,New York Knicks,29,53,0.354,30.0,104.5,108.0,-3.53,2018,NBA
11,Brooklyn Nets,28,54,0.341,31.0,106.6,110.3,-3.67,2018,NBA
12,Chicago Bulls,27,55,0.32899999999999996,32.0,102.9,110.0,-6.84,2018,NBA
13,Orlando Magic,25,57,0.305,34.0,103.4,108.2,-4.92,2018,NBA
14,Atlanta Hawks,24,58,0.293,35.0,103.4,108.8,-5.3,2018,NBA
15,Houston Rockets,65,17,0.7929999999999999,—,112.4,103.9,8.21,2018,NBA
16,Golden State Warriors,58,24,0.7070000000000001,7.0,113.5,107.5,5.79,2018,NBA
17,Portland Trail Blazers,49,33,0.598,16.0,105.6,103.0,2.6,2018,NBA
18,Oklahoma City Thunder,48,34,0.585,17.0,107.9,104.4,3.42,2018,NBA
19,Utah Jazz,48,34,0.585,17.0,104.1,99.8,4.47,2018,NBA
20,New Orleans Pelicans,48,34,0.585,17.0,111.7,110.4,1.48,2018,NBA
21,San Antonio Spurs,47,35,0.573,18.0,102.7,99.8,2.89,2018,NBA
22,Minnesota Timberwolves,47,35,0.573,18.0,109.5,107.3,2.35,2018,NBA
23,Denver Nuggets,46,36,0.561,19.0,110.0,108.5,1.57,2018,NBA
24,Los Angeles Clippers,42,40,0.512,23.0,109.0,109.0,0.15,2018,NBA
25,Los Angeles Lakers,35,47,0.42700000000000005,30.0,108.1,109.6,-1.44,2018,NBA
26,Sacramento Kings,27,55,0.32899999999999996,38.0,98.8,105.8,-6.6,2018,NBA
27,Dallas Mavericks,24,58,0.293,41.0,102.3,105.4,-2.7,2018,NBA
28,Memphis Grizzlies,22,60,0.268,43.0,99.3,105.5,-5.81,2018,NBA
29,Phoenix Suns,21,61,0.256,44.0,103.9,113.3,-8.8,2018,NBA

In [26]:
cities2.rename(columns={'Population (2016 est.)[8]':'Population'},inplace=True)

In [27]:
cities2=cities2[0:28]
cities2

,Metropolitan area,Country,Pop.rank,Population,B4,NFL,MLB,NBA,NHL,B6,MLS,CFL
0,New York City,United States,1,20153634,9,GiantsJets[note 1],YankeesMets[note 2],Knicks Nets,RangersIslandersDevils[note 3],11,Red BullsNew York City FC,—
1,Los Angeles,United States,2,13310447,8,RamsChargers[note 4],DodgersAngels,Lakers Clippers,KingsDucks,10,GalaxyLos Angeles FC[note 5],—
2,San Francisco Bay Area,United States,6,6657982,6,49ersRaiders[note 6],GiantsAthletics,Warriors,Sharks[note 7],7,Earthquakes,—
3,Chicago,United States,3,9512999,5,Bears[note 8],CubsWhite Sox,Bulls,Blackhawks,6,Fire,—
4,Dallas–Fort Worth,United States,4,7233323,4,Cowboys,Rangers,Mavericks,Stars,5,FC Dallas,—
5,"Washington, D.C.",United States,7,6131977,4,Redskins,Nationals[note 10],Wizards,Capitals,5,D.C. United,—
6,Philadelphia,United States,8,6070500,4,Eagles,Phillies[note 12],76ers,Flyers[note 13],5,Union,—
7,Boston,United States,12,4794447,4,Patriots[note 14],Red Sox[note 15],Celtics,Bruins,5,Revolution,—
8,Minneapolis–Saint Paul,United States,17,3551036,4,Vikings,Twins,Timberwolves,Wild[note 16],5,United FC,—
9,Denver,United States,20,2853077,4,Broncos,Rockies,Nuggets,Avalanche[note 18],5,Rapids,—
10,Miami–Fort Lauderdale,United States,9,6066387,4,Dolphins,Marlins,Heat,Panthers,4,[note 19],—
11,Phoenix,United States,13,4661537,4,Cardinals,Diamondbacks,Suns,Coyotes,4,—,—
12,Detroit,United States,14,4297617,4,Lions,Tigers[note 20],Pistons,Red Wings,4,—,—
13,Toronto,Canada,10,5928040,3,— [note 22],Blue Jays,Raptors,Maple Leafs,5,Toronto FC,Argonauts
14,Houston,United States,5,6772470,3,Texans[note 24],Astros,Rockets,—,4,Dynamo,—
15,Atlanta,United States,11,5789700,3,Falcons,Braves,Hawks,[note 25],4,United FC,—
18,Cleveland,United States,33,2055612,3,Browns[note 29],Indians[note 30],Cavaliers,[note 32],3,—,—
24,Charlotte,United States,23,2474314,2,Panthers,—,Hornets,—,2,—,—
25,Indianapolis,United States,35,2004230,2,Colts,[note 50],Pacers,—,2,—,—
27,Milwaukee,United States,37,1572482,2,[note 53],Brewers[note 54],Bucks,—,2,—,—
28,New Orleans,United States,45,1268883,2,Saints,—,Pelicans,—,2,—,—
32,Orlando,United States,25,2441257,1,—,—,Magic,—,2,Orlando City SC,—
33,Portland,United States,27,2424955,1,—,—,Trail Blazers,—,2,Timbers,—
38,Salt Lake City,United States,46,1186187,1,—,—,Jazz,—,2,Real Salt Lake,—
41,San Antonio,United States,26,2429609,1,[note 64],—,Spurs,—,1,—,[note 65]
42,Sacramento,United States,29,2296418,1,—,—,Kings,—,1,—,[note 66]
45,Oklahoma City,United States,40,1373211,1,—,—,Thunder,—,1,—,—
46,Memphis,United States,41,1342842,1,[note 69],—,Grizzlies,—,1,—,[note 70]

In [28]:
cities2['ratio_NBA']=0
for y in cities2['NBA']:
    Win=0
    Loss=0
    for r in y.split():
        print (r)
        if len(y)>0:
            n=cities2.loc[cities2['NBA']==y].index.values
            
        for x in nba_df2['team']:
            m=nba_df2.loc[nba_df2['team']==x].index.values
            if r in x and len(y)>0:
            #print("y:{}, x:{}".format(y,x))
                Win=Win+float(nba_df2.loc[m,'W'].values[0])
                Loss=Loss+float(nba_df2.loc[m,'L'].values[0])
                ratio=Win/(Win+Loss)
                cities2.loc[n,'ratio_NBA']=ratio
                break
population_by_region = list(cities2['Population']) # pass in metropolitan area population from cities
win_loss_by_region = list(cities2['ratio_NBA']) # pass in win/loss ratio from nba_df in the same order as cities["Metropolitan area"]
cities2['Population']=cities2['Population'].astype(float)
cities2['Population'].corr(cities2['ratio_NBA'])
cities2

Knicks
Nets
Lakers
Clippers
Warriors
Bulls
Mavericks
Wizards
76ers
Celtics
Timberwolves
Nuggets
Heat
Suns
Pistons
Raptors
Rockets
Hawks
Cavaliers
Hornets
Pacers
Bucks
Pelicans
Magic
Trail
Blazers
Jazz
Spurs
Kings
Thunder
Grizzlies

,Metropolitan area,Country,Pop.rank,Population,B4,NFL,MLB,NBA,NHL,B6,MLS,CFL,ratio_NBA
0,New York City,United States,1,20153634.0,9,GiantsJets[note 1],YankeesMets[note 2],Knicks Nets,RangersIslandersDevils[note 3],11,Red BullsNew York City FC,—,0.347561
1,Los Angeles,United States,2,13310447.0,8,RamsChargers[note 4],DodgersAngels,Lakers Clippers,KingsDucks,10,GalaxyLos Angeles FC[note 5],—,0.469512
2,San Francisco Bay Area,United States,6,6657982.0,6,49ersRaiders[note 6],GiantsAthletics,Warriors,Sharks[note 7],7,Earthquakes,—,0.707317
3,Chicago,United States,3,9512999.0,5,Bears[note 8],CubsWhite Sox,Bulls,Blackhawks,6,Fire,—,0.329268
4,Dallas–Fort Worth,United States,4,7233323.0,4,Cowboys,Rangers,Mavericks,Stars,5,FC Dallas,—,0.292683
5,"Washington, D.C.",United States,7,6131977.0,4,Redskins,Nationals[note 10],Wizards,Capitals,5,D.C. United,—,0.524390
6,Philadelphia,United States,8,6070500.0,4,Eagles,Phillies[note 12],76ers,Flyers[note 13],5,Union,—,0.634146
7,Boston,United States,12,4794447.0,4,Patriots[note 14],Red Sox[note 15],Celtics,Bruins,5,Revolution,—,0.670732
8,Minneapolis–Saint Paul,United States,17,3551036.0,4,Vikings,Twins,Timberwolves,Wild[note 16],5,United FC,—,0.573171
9,Denver,United States,20,2853077.0,4,Broncos,Rockies,Nuggets,Avalanche[note 18],5,Rapids,—,0.560976
10,Miami–Fort Lauderdale,United States,9,6066387.0,4,Dolphins,Marlins,Heat,Panthers,4,[note 19],—,0.536585
11,Phoenix,United States,13,4661537.0,4,Cardinals,Diamondbacks,Suns,Coyotes,4,—,—,0.256098
12,Detroit,United States,14,4297617.0,4,Lions,Tigers[note 20],Pistons,Red Wings,4,—,—,0.475610
13,Toronto,Canada,10,5928040.0,3,— [note 22],Blue Jays,Raptors,Maple Leafs,5,Toronto FC,Argonauts,0.719512
14,Houston,United States,5,6772470.0,3,Texans[note 24],Astros,Rockets,—,4,Dynamo,—,0.792683
15,Atlanta,United States,11,5789700.0,3,Falcons,Braves,Hawks,[note 25],4,United FC,—,0.292683
18,Cleveland,United States,33,2055612.0,3,Browns[note 29],Indians[note 30],Cavaliers,[note 32],3,—,—,0.609756
24,Charlotte,United States,23,2474314.0,2,Panthers,—,Hornets,—,2,—,—,0.439024
25,Indianapolis,United States,35,2004230.0,2,Colts,[note 50],Pacers,—,2,—,—,0.585366
27,Milwaukee,United States,37,1572482.0,2,[note 53],Brewers[note 54],Bucks,—,2,—,—,0.536585
28,New Orleans,United States,45,1268883.0,2,Saints,—,Pelicans,—,2,—,—,0.585366
32,Orlando,United States,25,2441257.0,1,—,—,Magic,—,2,Orlando City SC,—,0.304878
33,Portland,United States,27,2424955.0,1,—,—,Trail Blazers,—,2,Timbers,—,0.597561
38,Salt Lake City,United States,46,1186187.0,1,—,—,Jazz,—,2,Real Salt Lake,—,0.585366
41,San Antonio,United States,26,2429609.0,1,[note 64],—,Spurs,—,1,—,[note 65],0.573171
42,Sacramento,United States,29,2296418.0,1,—,—,Kings,—,1,—,[note 66],0.329268
45,Oklahoma City,United States,40,1373211.0,1,—,—,Thunder,—,1,—,—,0.585366
46,Memphis,United States,41,1342842.0,1,[note 69],—,Grizzlies,—,1,—,[note 70],0.268293

In [29]:
import pandas as pd
import numpy as np
import scipy.stats as stats
import re

nba_df=pd.read_csv("nba.csv")
cities=pd.read_html("wikipedia_data.html")[1]
cities=cities.iloc[:-1,[0,3,5,6,7,8]]

def nba_correlation():
    cities2=pd.DataFrame(cities, copy=True)
    cities2['NBA']=cities2['NBA'].str.replace('\[.*\]','',regex=True)
    cities2['NBA']=cities2['NBA'].str.extract('([A-Za-z0-9\s]+)')
    cities2['NBA'][cities2['NBA']=='KnicksNets']='Knicks Nets'
    cities2['NBA'][cities2['NBA']=='LakersClippers']='Lakers Clippers'
    cities2.dropna(subset=['NBA','Population (2016 est.)[8]'],inplace=True)   
    nba_df2=pd.DataFrame(nba_df, copy=True)
    nba_df2['team']=nba_df2['team'].str.extract('([a-zA-Z\s]+)')
    nba_df2=nba_df2[nba_df2['year']==2018]
    nba_df2['team'][nba_df2['team']=='Philadelphia ']='Philadelphia 76ers'  
    cities2.rename(columns={'Population (2016 est.)[8]':'Population'},inplace=True)
    cities2=cities2[0:28]
    cities2['ratio_NBA']=0
    for y in cities2['NBA']:
        Win=0
        Loss=0
        for r in y.split():
            if len(y)>0:
                n=cities2.loc[cities2['NBA']==y].index.values
                
            for x in nba_df2['team']:
                m=nba_df2.loc[nba_df2['team']==x].index.values
                if r in x and len(y)>0:
                #print("y:{}, x:{}".format(y,x))
                    Win=Win+float(nba_df2.loc[m,'W'].values[0])
                    Loss=Loss+float(nba_df2.loc[m,'L'].values[0])
                    ratio=Win/(Win+Loss)
                    cities2.loc[n,'ratio_NBA']=ratio
                    break   
    cities2['Population']=cities2['Population'].astype(float)
    
    #print(resultDf)
    population_by_region = list(cities2['Population']) # pass in metropolitan area population from cities
    win_loss_by_region = list(cities2['ratio_NBA']) # pass in win/loss ratio from nba_df in the same order as cities["Metropolitan area"]

    assert len(population_by_region) == len(win_loss_by_region), "Q2: Your lists must be the same length"
    assert len(population_by_region) == 28, "Q2: There should be 28 teams being analysed for NBA"

    return cities2['Population'].corr(cities2['ratio_NBA'])
nba_correlation()

-0.1765716025284463

## Question 3
For this question, calculate the win/loss ratio's correlation with the population of the city it is in for the **MLB** using **2018** data.

In [30]:
mlb_df=pd.read_csv("mlb.csv")
cities=pd.read_html("wikipedia_data.html")[1]
cities=cities.iloc[:-1,[0,3,5,6,7,8]]

In [31]:
mlb_df2=mlb_df[mlb_df['year']==2018]
mlb_df2

                     team    W    L   W-L%    GB  year League
0          Boston Red Sox  108   54  0.667    --  2018    MLB
1        New York Yankees  100   62  0.617   8.0  2018    MLB
2          Tampa Bay Rays   90   72  0.556  18.0  2018    MLB
3       Toronto Blue Jays   73   89  0.451  35.0  2018    MLB
4       Baltimore Orioles   47  115  0.290  61.0  2018    MLB
5       Cleveland Indians   91   71  0.562    --  2018    MLB
6         Minnesota Twins   78   84  0.481  13.0  2018    MLB
7          Detroit Tigers   64   98  0.395  27.0  2018    MLB
8       Chicago White Sox   62  100  0.383  29.0  2018    MLB
9      Kansas City Royals   58  104  0.358  33.0  2018    MLB
10         Houston Astros  103   59  0.636    --  2018    MLB
11      Oakland Athletics   97   65  0.599   6.0  2018    MLB
12       Seattle Mariners   89   73  0.549  14.0  2018    MLB
13     Los Angeles Angels   80   82  0.494  23.0  2018    MLB
14          Texas Rangers   67   95  0.414  36.0  2018    MLB
15         Atlanta Braves   90   72  0.556    --  2018    MLB
16   Washington Nationals   82   80  0.506   8.0  2018    MLB
17  Philadelphia Phillies   80   82  0.494  10.0  2018    MLB
18          New York Mets   77   85  0.475  13.0  2018    MLB
19          Miami Marlins   63   98  0.391  26.5  2018    MLB
20      Milwaukee Brewers   96   67  0.589    --  2018    MLB
21           Chicago Cubs   95   68  0.583   1.0  2018    MLB
22    St. Louis Cardinals   88   74  0.543   7.5  2018    MLB
23     Pittsburgh Pirates   82   79  0.509  13.0  2018    MLB
24        Cincinnati Reds   67   95  0.414  28.5  2018    MLB
25    Los Angeles Dodgers   92   71  0.564    --  2018    MLB
26       Colorado Rockies   91   72  0.558   1.0  2018    MLB
27   Arizona Diamondbacks   82   80  0.506   9.5  2018    MLB
28   San Francisco Giants   73   89  0.451  18.5  2018    MLB
29       San Diego Padres   66   96  0.407  25.5  2018    MLB

In [32]:
cities['MLB']

0     YankeesMets[note 2]
1           DodgersAngels
2         GiantsAthletics
3           CubsWhite Sox
4                 Rangers
5      Nationals[note 10]
6       Phillies[note 12]
7        Red Sox[note 15]
8                   Twins
9                 Rockies
10                Marlins
11           Diamondbacks
12        Tigers[note 20]
13              Blue Jays
14                 Astros
15                 Braves
16                   Rays
17                Pirates
18       Indians[note 30]
19               Mariners
20          Reds[note 35]
21        Royals[note 37]
22     Cardinals[note 41]
23       Orioles[note 46]
24                      —
25              [note 50]
26                      —
27       Brewers[note 54]
28                      —
29              [note 57]
30              [note 59]
31                      —
32                      —
33                      —
34                      —
35                      —
36                      —
37                      —
38                      —
39                      —
40                 Padres
41                      —
42                      —
43                      —
44                      —
45                      —
46                      —
47                      —
48                      —
49                      —
50                      —
Name: MLB, dtype: object

In [33]:
cities['MLB']=cities['MLB'].str.replace('\[.*\]','',regex=True)

In [34]:
cities['MLB']=cities['MLB'].str.extract('([A-Za-z0-9\s]+)')
cities.dropna(subset=['MLB'],inplace=True)
cities

,Metropolitan area,Population (2016 est.)[8],NFL,MLB,NBA,NHL
0,New York City,20153634,GiantsJets[note 1],YankeesMets,KnicksNets,RangersIslandersDevils[note 3]
1,Los Angeles,13310447,RamsChargers[note 4],DodgersAngels,LakersClippers,KingsDucks
2,San Francisco Bay Area,6657982,49ersRaiders[note 6],GiantsAthletics,Warriors,Sharks[note 7]
3,Chicago,9512999,Bears[note 8],CubsWhite Sox,Bulls[note 9],Blackhawks
4,Dallas–Fort Worth,7233323,Cowboys,Rangers,Mavericks,Stars
5,"Washington, D.C.",6131977,Redskins,Nationals,Wizards[note 11],Capitals
6,Philadelphia,6070500,Eagles,Phillies,76ers,Flyers[note 13]
7,Boston,4794447,Patriots[note 14],Red Sox,Celtics,Bruins
8,Minneapolis–Saint Paul,3551036,Vikings,Twins,Timberwolves,Wild[note 16]
9,Denver,2853077,Broncos,Rockies,Nuggets[note 17],Avalanche[note 18]
10,Miami–Fort Lauderdale,6066387,Dolphins,Marlins,Heat,Panthers
11,Phoenix,4661537,Cardinals,Diamondbacks,Suns,Coyotes
12,Detroit,4297617,Lions,Tigers,Pistons[note 21],Red Wings
13,Toronto,5928040,— [note 22],Blue Jays,Raptors[note 23],Maple Leafs
14,Houston,6772470,Texans[note 24],Astros,Rockets,—
15,Atlanta,5789700,Falcons,Braves,Hawks,[note 25]
16,Tampa Bay Area,3032171,Buccaneers,Rays,—,Lightning
17,Pittsburgh,2342299,Steelers,Pirates,[note 27],Penguins[note 28]
18,Cleveland,2055612,Browns[note 29],Indians,Cavaliers[note 31],[note 32]
19,Seattle,3798902,Seahawks,Mariners,[note 33],[note 34]
20,Cincinnati,2165139,Bengals,Reds,[note 36],—
21,Kansas City,2104509,Chiefs,Royals,[note 38],[note 39]
22,St. Louis,2807002,[note 40],Cardinals,[note 42],Blues[note 43]
23,Baltimore,2798886,Ravens[note 45],Orioles,[note 47],—
27,Milwaukee,1572482,[note 53],Brewers,Bucks,—
40,San Diego,3317749,[note 62],Padres,[note 63],—

In [35]:
cities['MLB'][cities['MLB']=='YankeesMets']='Yankees,Mets'
cities['MLB'][cities['MLB']=='CubsWhite Sox']='Cubs,White Sox'
cities['MLB'][cities['MLB']=='DodgersAngels']='Dodgers,Angels'
cities['MLB'][cities['MLB']=='GiantsAthletics']='Giants,Athletics'
cities

,Metropolitan area,Population (2016 est.)[8],NFL,MLB,NBA,NHL
0,New York City,20153634,GiantsJets[note 1],"Yankees,Mets",KnicksNets,RangersIslandersDevils[note 3]
1,Los Angeles,13310447,RamsChargers[note 4],"Dodgers,Angels",LakersClippers,KingsDucks
2,San Francisco Bay Area,6657982,49ersRaiders[note 6],"Giants,Athletics",Warriors,Sharks[note 7]
3,Chicago,9512999,Bears[note 8],"Cubs,White Sox",Bulls[note 9],Blackhawks
4,Dallas–Fort Worth,7233323,Cowboys,Rangers,Mavericks,Stars
5,"Washington, D.C.",6131977,Redskins,Nationals,Wizards[note 11],Capitals
6,Philadelphia,6070500,Eagles,Phillies,76ers,Flyers[note 13]
7,Boston,4794447,Patriots[note 14],Red Sox,Celtics,Bruins
8,Minneapolis–Saint Paul,3551036,Vikings,Twins,Timberwolves,Wild[note 16]
9,Denver,2853077,Broncos,Rockies,Nuggets[note 17],Avalanche[note 18]
10,Miami–Fort Lauderdale,6066387,Dolphins,Marlins,Heat,Panthers
11,Phoenix,4661537,Cardinals,Diamondbacks,Suns,Coyotes
12,Detroit,4297617,Lions,Tigers,Pistons[note 21],Red Wings
13,Toronto,5928040,— [note 22],Blue Jays,Raptors[note 23],Maple Leafs
14,Houston,6772470,Texans[note 24],Astros,Rockets,—
15,Atlanta,5789700,Falcons,Braves,Hawks,[note 25]
16,Tampa Bay Area,3032171,Buccaneers,Rays,—,Lightning
17,Pittsburgh,2342299,Steelers,Pirates,[note 27],Penguins[note 28]
18,Cleveland,2055612,Browns[note 29],Indians,Cavaliers[note 31],[note 32]
19,Seattle,3798902,Seahawks,Mariners,[note 33],[note 34]
20,Cincinnati,2165139,Bengals,Reds,[note 36],—
21,Kansas City,2104509,Chiefs,Royals,[note 38],[note 39]
22,St. Louis,2807002,[note 40],Cardinals,[note 42],Blues[note 43]
23,Baltimore,2798886,Ravens[note 45],Orioles,[note 47],—
27,Milwaukee,1572482,[note 53],Brewers,Bucks,—
40,San Diego,3317749,[note 62],Padres,[note 63],—

In [36]:
cities['MLB_ratio']=0
for y in cities['MLB']:
    Win=0
    Loss=0
    for r in y.split(','):
        n=cities.loc[cities['MLB']==y].index.values
        for x in mlb_df['team']:
                m=mlb_df.loc[mlb_df['team']==x].index.values
                if r in x and len(y)>0:
            #print("y:{}, x:{}".format(y,x))
                    Win=Win+float(mlb_df.loc[m,'W'].values[0])
                    Loss=Loss+float(mlb_df.loc[m,'L'].values[0])
                    ratio=Win/(Win+Loss)
                    cities.loc[n,'MLB_ratio']=ratio
                    break
cities

,Metropolitan area,Population (2016 est.)[8],NFL,MLB,NBA,NHL,MLB_ratio
0,New York City,20153634,GiantsJets[note 1],"Yankees,Mets",KnicksNets,RangersIslandersDevils[note 3],0.546296
1,Los Angeles,13310447,RamsChargers[note 4],"Dodgers,Angels",LakersClippers,KingsDucks,0.529231
2,San Francisco Bay Area,6657982,49ersRaiders[note 6],"Giants,Athletics",Warriors,Sharks[note 7],0.524691
3,Chicago,9512999,Bears[note 8],"Cubs,White Sox",Bulls[note 9],Blackhawks,0.483077
4,Dallas–Fort Worth,7233323,Cowboys,Rangers,Mavericks,Stars,0.413580
5,"Washington, D.C.",6131977,Redskins,Nationals,Wizards[note 11],Capitals,0.506173
6,Philadelphia,6070500,Eagles,Phillies,76ers,Flyers[note 13],0.493827
7,Boston,4794447,Patriots[note 14],Red Sox,Celtics,Bruins,0.666667
8,Minneapolis–Saint Paul,3551036,Vikings,Twins,Timberwolves,Wild[note 16],0.481481
9,Denver,2853077,Broncos,Rockies,Nuggets[note 17],Avalanche[note 18],0.558282
10,Miami–Fort Lauderdale,6066387,Dolphins,Marlins,Heat,Panthers,0.391304
11,Phoenix,4661537,Cardinals,Diamondbacks,Suns,Coyotes,0.506173
12,Detroit,4297617,Lions,Tigers,Pistons[note 21],Red Wings,0.395062
13,Toronto,5928040,— [note 22],Blue Jays,Raptors[note 23],Maple Leafs,0.450617
14,Houston,6772470,Texans[note 24],Astros,Rockets,—,0.635802
15,Atlanta,5789700,Falcons,Braves,Hawks,[note 25],0.555556
16,Tampa Bay Area,3032171,Buccaneers,Rays,—,Lightning,0.555556
17,Pittsburgh,2342299,Steelers,Pirates,[note 27],Penguins[note 28],0.509317
18,Cleveland,2055612,Browns[note 29],Indians,Cavaliers[note 31],[note 32],0.561728
19,Seattle,3798902,Seahawks,Mariners,[note 33],[note 34],0.549383
20,Cincinnati,2165139,Bengals,Reds,[note 36],—,0.413580
21,Kansas City,2104509,Chiefs,Royals,[note 38],[note 39],0.358025
22,St. Louis,2807002,[note 40],Cardinals,[note 42],Blues[note 43],0.543210
23,Baltimore,2798886,Ravens[note 45],Orioles,[note 47],—,0.290123
27,Milwaukee,1572482,[note 53],Brewers,Bucks,—,0.588957
40,San Diego,3317749,[note 62],Padres,[note 63],—,0.407407

In [37]:
import pandas as pd
import numpy as np
import scipy.stats as stats
import re

mlb_df=pd.read_csv("mlb.csv")
cities=pd.read_html("wikipedia_data.html")[1]
cities=cities.iloc[:-1,[0,3,5,6,7,8]]

def mlb_correlation(): 
    mlb_df2=mlb_df[mlb_df['year']==2018]
    cities.columns = cities.columns.str.strip()
    assert('Population (2016 est.)[8]' in cities.columns)
    cities.rename(columns={'Population (2016 est.)[8]':'Population'},inplace=True)
    cities['MLB']=cities['MLB'].str.replace('\[.*\]','',regex=True)
    cities['MLB']=cities['MLB'].str.extract('([A-Za-z0-9\s]+)')
    cities.dropna(subset=['MLB'],inplace=True)
    cities['MLB'][cities['MLB']=='YankeesMets']='Yankees,Mets'
    cities['MLB'][cities['MLB']=='CubsWhite Sox']='Cubs,White Sox'
    cities['MLB'][cities['MLB']=='DodgersAngels']='Dodgers,Angels'
    cities['MLB'][cities['MLB']=='GiantsAthletics']='Giants,Athletics'
    cities['MLB_ratio']=0
    for y in cities['MLB']:
        Win=0
        Loss=0
        for r in y.split(','):
            n=cities.loc[cities['MLB']==y].index.values
            for x in mlb_df['team']:
                    m=mlb_df.loc[mlb_df['team']==x].index.values
                    if r in x and len(y)>0:
                #print("y:{}, x:{}".format(y,x))
                        Win=Win+float(mlb_df.loc[m,'W'].values[0])
                        Loss=Loss+float(mlb_df.loc[m,'L'].values[0])
                        ratio=Win/(Win+Loss)
                        cities.loc[n,'MLB_ratio']=ratio
                        break
    cities['Population']=cities['Population'].astype(int)
    population_by_region = list(cities['Population']) # pass in metropolitan area population from cities
    win_loss_by_region = list(cities['MLB_ratio']) # pass in win/loss ratio from mlb_df in the same order as cities["Metropolitan area"]
    # resultDf = pd.DataFrame(cities[["Metropolitan area", "Population", "MLB_ratio"]], copy=True)
    # print(resultDf.sort_values(by='Metropolitan area'))
    assert len(population_by_region) == len(win_loss_by_region), "Q3: Your lists must be the same length"
    assert len(population_by_region) == 26, "Q3: There should be 26 teams being analysed for MLB"

    return stats.pearsonr(population_by_region, win_loss_by_region)[0]
mlb_correlation()

0.15052304487104848

## Question 4
For this question, calculate the win/loss ratio's correlation with the population of the city it is in for the **NFL** using **2018** data.

In [38]:
nfl_df=pd.read_csv("nfl.csv")
cities=pd.read_html("wikipedia_data.html")[1]
cities=cities.iloc[:-1,[0,3,5,6,7,8]]

In [39]:
nfl_df2=nfl_df[(nfl_df['year']==2018) & (nfl_df['L'].str.contains('([0-9]+)'))]
nfl_df2

,DSRS,L,League,MoV,OSRS,PA,PD,PF,SRS,SoS,T,W,W-L%,team,year
1,2.1,5,NFL,6.9,3.1,325,111,436,5.2,-1.8,0,11,.688,New England Patriots*,2018
2,-5.2,9,NFL,-7.1,-3.6,433,-114,319,-8.8,-1.7,0,7,.438,Miami Dolphins,2018
3,-0.6,10,NFL,-6.6,-6.3,374,-105,269,-6.9,-0.3,0,6,.375,Buffalo Bills,2018
4,-5.9,12,NFL,-6.8,-2.0,441,-108,333,-7.8,-1.1,0,4,.250,New York Jets,2018
6,6.4,6,NFL,6.4,0.6,287,102,389,7.0,0.6,0,10,.625,Baltimore Ravens*,2018
7,1.7,6,NFL,4.3,3.9,360,68,428,5.6,1.3,1,9,.594,Pittsburgh Steelers,2018
8,0.6,8,NFL,-2.1,-1.0,392,-33,359,-0.3,1.7,1,7,.469,Cleveland Browns,2018
9,-3.4,10,NFL,-5.4,0.0,455,-87,368,-3.4,2.0,0,6,.375,Cincinnati Bengals,2018
11,1.4,5,NFL,5.4,2.4,316,86,402,3.8,-1.5,0,11,.688,Houston Texans*,2018
12,-0.6,6,NFL,5.6,3.9,344,89,433,3.4,-2.2,0,10,.625,Indianapolis Colts+,2018
13,3.5,7,NFL,0.4,-3.2,303,7,310,0.2,-0.2,0,9,.563,Tennessee Titans,2018
14,4.0,11,NFL,-4.4,-8.1,316,-71,245,-4.0,0.4,0,5,.313,Jacksonville Jaguars,2018
16,-3.8,4,NFL,9.0,12.6,421,144,565,8.9,-0.1,0,12,.750,Kansas City Chiefs*,2018
17,2.9,4,NFL,6.2,3.0,329,99,428,6.0,-0.2,0,12,.750,Los Angeles Chargers+,2018
18,3.1,10,NFL,-1.3,-3.6,349,-20,329,-0.5,0.7,0,6,.375,Denver Broncos,2018
19,-4.1,12,NFL,-11.1,-5.2,467,-177,290,-9.3,1.8,0,4,.250,Oakland Raiders,2018
21,2.9,6,NFL,0.9,-1.9,324,15,339,1.1,0.2,0,10,.625,Dallas Cowboys*,2018
22,1.8,7,NFL,1.2,0.0,348,19,367,1.7,0.5,0,9,.563,Philadelphia Eagles+,2018
23,0.6,9,NFL,-4.9,-5.6,359,-78,281,-4.9,-0.1,0,7,.438,Washington Redskins,2018
24,-2.9,11,NFL,-2.7,0.8,412,-43,369,-2.2,0.5,0,5,.313,New York Giants,2018
26,4.8,4,NFL,8.6,1.5,283,138,421,6.3,-2.3,0,12,.750,Chicago Bears*,2018
27,1.8,7,NFL,1.2,-1.2,341,19,360,0.6,-0.6,1,8,.531,Minnesota Vikings,2018
28,-2.7,9,NFL,-1.5,0.0,400,-24,376,-2.7,-1.2,1,6,.406,Green Bay Packers,2018
29,0.3,10,NFL,-2.3,-3.3,360,-36,324,-3.0,-0.8,0,6,.375,Detroit Lions,2018
31,2.2,3,NFL,9.4,7.9,353,151,504,10.1,0.6,0,13,.813,New Orleans Saints*,2018
32,0.8,9,NFL,-0.4,0.1,382,-6,376,0.9,1.3,0,7,.438,Carolina Panthers,2018
33,-2.6,9,NFL,-0.6,2.5,423,-9,414,-0.1,0.4,0,7,.438,Atlanta Falcons,2018
34,-4.6,11,NFL,-4.3,2.0,464,-68,396,-2.6,1.7,0,5,.313,Tampa Bay Buccaneers,2018
36,-1.1,3,NFL,8.9,9.5,384,143,527,8.5,-0.4,0,13,.813,Los Angeles Rams*,2018
37,1.5,6,NFL,5.1,3.0,347,81,428,4.5,-0.6,0,10,.625,Seattle Seahawks+,2018
38,-3.1,12,NFL,-5.8,-2.5,435,-93,342,-5.5,0.3,0,4,.250,San Francisco 49ers,2018
39,-1.9,13,NFL,-12.5,-9.6,425,-200,225,-11.5,1.0,0,3,.188,Arizona Cardinals,2018

In [40]:
nfl_df2['team']=nfl_df2['team'].str.extract('([a-zA-Z\s]+)')
nfl_df2

,DSRS,L,League,MoV,OSRS,PA,PD,PF,SRS,SoS,T,W,W-L%,team,year
1,2.1,5,NFL,6.9,3.1,325,111,436,5.2,-1.8,0,11,.688,New England Patriots,2018
2,-5.2,9,NFL,-7.1,-3.6,433,-114,319,-8.8,-1.7,0,7,.438,Miami Dolphins,2018
3,-0.6,10,NFL,-6.6,-6.3,374,-105,269,-6.9,-0.3,0,6,.375,Buffalo Bills,2018
4,-5.9,12,NFL,-6.8,-2.0,441,-108,333,-7.8,-1.1,0,4,.250,New York Jets,2018
6,6.4,6,NFL,6.4,0.6,287,102,389,7.0,0.6,0,10,.625,Baltimore Ravens,2018
7,1.7,6,NFL,4.3,3.9,360,68,428,5.6,1.3,1,9,.594,Pittsburgh Steelers,2018
8,0.6,8,NFL,-2.1,-1.0,392,-33,359,-0.3,1.7,1,7,.469,Cleveland Browns,2018
9,-3.4,10,NFL,-5.4,0.0,455,-87,368,-3.4,2.0,0,6,.375,Cincinnati Bengals,2018
11,1.4,5,NFL,5.4,2.4,316,86,402,3.8,-1.5,0,11,.688,Houston Texans,2018
12,-0.6,6,NFL,5.6,3.9,344,89,433,3.4,-2.2,0,10,.625,Indianapolis Colts,2018
13,3.5,7,NFL,0.4,-3.2,303,7,310,0.2,-0.2,0,9,.563,Tennessee Titans,2018
14,4.0,11,NFL,-4.4,-8.1,316,-71,245,-4.0,0.4,0,5,.313,Jacksonville Jaguars,2018
16,-3.8,4,NFL,9.0,12.6,421,144,565,8.9,-0.1,0,12,.750,Kansas City Chiefs,2018
17,2.9,4,NFL,6.2,3.0,329,99,428,6.0,-0.2,0,12,.750,Los Angeles Chargers,2018
18,3.1,10,NFL,-1.3,-3.6,349,-20,329,-0.5,0.7,0,6,.375,Denver Broncos,2018
19,-4.1,12,NFL,-11.1,-5.2,467,-177,290,-9.3,1.8,0,4,.250,Oakland Raiders,2018
21,2.9,6,NFL,0.9,-1.9,324,15,339,1.1,0.2,0,10,.625,Dallas Cowboys,2018
22,1.8,7,NFL,1.2,0.0,348,19,367,1.7,0.5,0,9,.563,Philadelphia Eagles,2018
23,0.6,9,NFL,-4.9,-5.6,359,-78,281,-4.9,-0.1,0,7,.438,Washington Redskins,2018
24,-2.9,11,NFL,-2.7,0.8,412,-43,369,-2.2,0.5,0,5,.313,New York Giants,2018
26,4.8,4,NFL,8.6,1.5,283,138,421,6.3,-2.3,0,12,.750,Chicago Bears,2018
27,1.8,7,NFL,1.2,-1.2,341,19,360,0.6,-0.6,1,8,.531,Minnesota Vikings,2018
28,-2.7,9,NFL,-1.5,0.0,400,-24,376,-2.7,-1.2,1,6,.406,Green Bay Packers,2018
29,0.3,10,NFL,-2.3,-3.3,360,-36,324,-3.0,-0.8,0,6,.375,Detroit Lions,2018
31,2.2,3,NFL,9.4,7.9,353,151,504,10.1,0.6,0,13,.813,New Orleans Saints,2018
32,0.8,9,NFL,-0.4,0.1,382,-6,376,0.9,1.3,0,7,.438,Carolina Panthers,2018
33,-2.6,9,NFL,-0.6,2.5,423,-9,414,-0.1,0.4,0,7,.438,Atlanta Falcons,2018
34,-4.6,11,NFL,-4.3,2.0,464,-68,396,-2.6,1.7,0,5,.313,Tampa Bay Buccaneers,2018
36,-1.1,3,NFL,8.9,9.5,384,143,527,8.5,-0.4,0,13,.813,Los Angeles Rams,2018
37,1.5,6,NFL,5.1,3.0,347,81,428,4.5,-0.6,0,10,.625,Seattle Seahawks,2018
38,-3.1,12,NFL,-5.8,-2.5,435,-93,342,-5.5,0.3,0,4,.250,San Francisco,2018
39,-1.9,13,NFL,-12.5,-9.6,425,-200,225,-11.5,1.0,0,3,.188,Arizona Cardinals,2018

In [41]:
cities['NFL']=cities['NFL'].str.replace('\[.*\]','',regex=True)
cities['NFL']=cities['NFL'].str.extract('([a-zA-Z0-9]+)')
cities.dropna(subset=['NFL'],inplace=True)
cities

,Metropolitan area,Population (2016 est.)[8],NFL,MLB,NBA,NHL
0,New York City,20153634,GiantsJets,YankeesMets[note 2],KnicksNets,RangersIslandersDevils[note 3]
1,Los Angeles,13310447,RamsChargers,DodgersAngels,LakersClippers,KingsDucks
2,San Francisco Bay Area,6657982,49ersRaiders,GiantsAthletics,Warriors,Sharks[note 7]
3,Chicago,9512999,Bears,CubsWhite Sox,Bulls[note 9],Blackhawks
4,Dallas–Fort Worth,7233323,Cowboys,Rangers,Mavericks,Stars
5,"Washington, D.C.",6131977,Redskins,Nationals[note 10],Wizards[note 11],Capitals
6,Philadelphia,6070500,Eagles,Phillies[note 12],76ers,Flyers[note 13]
7,Boston,4794447,Patriots,Red Sox[note 15],Celtics,Bruins
8,Minneapolis–Saint Paul,3551036,Vikings,Twins,Timberwolves,Wild[note 16]
9,Denver,2853077,Broncos,Rockies,Nuggets[note 17],Avalanche[note 18]
10,Miami–Fort Lauderdale,6066387,Dolphins,Marlins,Heat,Panthers
11,Phoenix,4661537,Cardinals,Diamondbacks,Suns,Coyotes
12,Detroit,4297617,Lions,Tigers[note 20],Pistons[note 21],Red Wings
14,Houston,6772470,Texans,Astros,Rockets,—
15,Atlanta,5789700,Falcons,Braves,Hawks,[note 25]
16,Tampa Bay Area,3032171,Buccaneers,Rays,—,Lightning
17,Pittsburgh,2342299,Steelers,Pirates,[note 27],Penguins[note 28]
18,Cleveland,2055612,Browns,Indians[note 30],Cavaliers[note 31],[note 32]
19,Seattle,3798902,Seahawks,Mariners,[note 33],[note 34]
20,Cincinnati,2165139,Bengals,Reds[note 35],[note 36],—
21,Kansas City,2104509,Chiefs,Royals[note 37],[note 38],[note 39]
23,Baltimore,2798886,Ravens,Orioles[note 46],[note 47],—
24,Charlotte,2474314,Panthers,—,Hornets[note 49],—
25,Indianapolis,2004230,Colts,[note 50],Pacers[note 51],—
26,Nashville,1865298,Titans,—,—,Predators
28,New Orleans,1268883,Saints,—,Pelicans[note 55],—
29,Buffalo,1132804,Bills,[note 57],[note 58],Sabres
44,Jacksonville,1478212,Jaguars,—,—,—
48,Green Bay,318236,Packers,—,—,—

In [42]:
cities['NFL'][cities['NFL']=='GiantsJets']='Giants,Jets'
cities['NFL'][cities['NFL']=='RamsChargers']='Rams,Chargers'
cities['NFL'][cities['NFL']=='49ersRaiders']='49ers,Raiders'

In [43]:
cities

,Metropolitan area,Population (2016 est.)[8],NFL,MLB,NBA,NHL
0,New York City,20153634,"Giants,Jets",YankeesMets[note 2],KnicksNets,RangersIslandersDevils[note 3]
1,Los Angeles,13310447,"Rams,Chargers",DodgersAngels,LakersClippers,KingsDucks
2,San Francisco Bay Area,6657982,"49ers,Raiders",GiantsAthletics,Warriors,Sharks[note 7]
3,Chicago,9512999,Bears,CubsWhite Sox,Bulls[note 9],Blackhawks
4,Dallas–Fort Worth,7233323,Cowboys,Rangers,Mavericks,Stars
5,"Washington, D.C.",6131977,Redskins,Nationals[note 10],Wizards[note 11],Capitals
6,Philadelphia,6070500,Eagles,Phillies[note 12],76ers,Flyers[note 13]
7,Boston,4794447,Patriots,Red Sox[note 15],Celtics,Bruins
8,Minneapolis–Saint Paul,3551036,Vikings,Twins,Timberwolves,Wild[note 16]
9,Denver,2853077,Broncos,Rockies,Nuggets[note 17],Avalanche[note 18]
10,Miami–Fort Lauderdale,6066387,Dolphins,Marlins,Heat,Panthers
11,Phoenix,4661537,Cardinals,Diamondbacks,Suns,Coyotes
12,Detroit,4297617,Lions,Tigers[note 20],Pistons[note 21],Red Wings
14,Houston,6772470,Texans,Astros,Rockets,—
15,Atlanta,5789700,Falcons,Braves,Hawks,[note 25]
16,Tampa Bay Area,3032171,Buccaneers,Rays,—,Lightning
17,Pittsburgh,2342299,Steelers,Pirates,[note 27],Penguins[note 28]
18,Cleveland,2055612,Browns,Indians[note 30],Cavaliers[note 31],[note 32]
19,Seattle,3798902,Seahawks,Mariners,[note 33],[note 34]
20,Cincinnati,2165139,Bengals,Reds[note 35],[note 36],—
21,Kansas City,2104509,Chiefs,Royals[note 37],[note 38],[note 39]
23,Baltimore,2798886,Ravens,Orioles[note 46],[note 47],—
24,Charlotte,2474314,Panthers,—,Hornets[note 49],—
25,Indianapolis,2004230,Colts,[note 50],Pacers[note 51],—
26,Nashville,1865298,Titans,—,—,Predators
28,New Orleans,1268883,Saints,—,Pelicans[note 55],—
29,Buffalo,1132804,Bills,[note 57],[note 58],Sabres
44,Jacksonville,1478212,Jaguars,—,—,—
48,Green Bay,318236,Packers,—,—,—

In [44]:
cities.rename(columns={'Population (2016 est.)[8]':'Population'},inplace=True)

In [45]:
cities['NFL_ratio']=0
for y in cities['NFL']:
        Win=0
        Loss=0
        for r in y.split(','):
            n=cities.loc[cities['NFL']==y].index.values
            for x in nfl_df2['team']:
                    m = nfl_df2.loc[nfl_df2['team']==x].index.values
                    if r in x and len(y)>0:
                #print("y:{}, x:{}".format(y,x))
                        Win=Win+float (nfl_df2.loc[m,'W'].values[0])
                        Loss=Loss+float (nfl_df2.loc[m,'L'].values[0])
                        ratio=Win/(Win+Loss)
                        cities.loc[n,'NFL_ratio']=ratio
                        break
cities['Population']=cities['Population'].astype(int)
cities

,Metropolitan area,Population,NFL,MLB,NBA,NHL,NFL_ratio
0,New York City,20153634,"Giants,Jets",YankeesMets[note 2],KnicksNets,RangersIslandersDevils[note 3],0.281250
1,Los Angeles,13310447,"Rams,Chargers",DodgersAngels,LakersClippers,KingsDucks,0.781250
2,San Francisco Bay Area,6657982,"49ers,Raiders",GiantsAthletics,Warriors,Sharks[note 7],0.250000
3,Chicago,9512999,Bears,CubsWhite Sox,Bulls[note 9],Blackhawks,0.750000
4,Dallas–Fort Worth,7233323,Cowboys,Rangers,Mavericks,Stars,0.625000
5,"Washington, D.C.",6131977,Redskins,Nationals[note 10],Wizards[note 11],Capitals,0.437500
6,Philadelphia,6070500,Eagles,Phillies[note 12],76ers,Flyers[note 13],0.562500
7,Boston,4794447,Patriots,Red Sox[note 15],Celtics,Bruins,0.687500
8,Minneapolis–Saint Paul,3551036,Vikings,Twins,Timberwolves,Wild[note 16],0.533333
9,Denver,2853077,Broncos,Rockies,Nuggets[note 17],Avalanche[note 18],0.375000
10,Miami–Fort Lauderdale,6066387,Dolphins,Marlins,Heat,Panthers,0.437500
11,Phoenix,4661537,Cardinals,Diamondbacks,Suns,Coyotes,0.187500
12,Detroit,4297617,Lions,Tigers[note 20],Pistons[note 21],Red Wings,0.375000
14,Houston,6772470,Texans,Astros,Rockets,—,0.687500
15,Atlanta,5789700,Falcons,Braves,Hawks,[note 25],0.437500
16,Tampa Bay Area,3032171,Buccaneers,Rays,—,Lightning,0.312500
17,Pittsburgh,2342299,Steelers,Pirates,[note 27],Penguins[note 28],0.600000
18,Cleveland,2055612,Browns,Indians[note 30],Cavaliers[note 31],[note 32],0.466667
19,Seattle,3798902,Seahawks,Mariners,[note 33],[note 34],0.625000
20,Cincinnati,2165139,Bengals,Reds[note 35],[note 36],—,0.375000
21,Kansas City,2104509,Chiefs,Royals[note 37],[note 38],[note 39],0.750000
23,Baltimore,2798886,Ravens,Orioles[note 46],[note 47],—,0.625000
24,Charlotte,2474314,Panthers,—,Hornets[note 49],—,0.437500
25,Indianapolis,2004230,Colts,[note 50],Pacers[note 51],—,0.625000
26,Nashville,1865298,Titans,—,—,Predators,0.562500
28,New Orleans,1268883,Saints,—,Pelicans[note 55],—,0.812500
29,Buffalo,1132804,Bills,[note 57],[note 58],Sabres,0.375000
44,Jacksonville,1478212,Jaguars,—,—,—,0.312500
48,Green Bay,318236,Packers,—,—,—,0.400000

In [46]:
import pandas as pd
import numpy as np
import scipy.stats as stats
import re

nfl_df=pd.read_csv("nfl.csv")
cities_old=pd.read_html("wikipedia_data.html")[1]
cities_old=cities_old.iloc[:-1,[0,3,5,6,7,8]]

def nfl_correlation():
    cities=pd.DataFrame(cities_old, copy=True)
    cities.columns = cities.columns.str.strip()
    nfl_df2=pd.DataFrame(nfl_df[(nfl_df['year']==2018) & (nfl_df['L'].str.contains('([0-9]+)'))],copy=True)
    nfl_df2['team']=nfl_df2['team'].str.extract('([a-zA-Z\s]+)')
    cities.rename(columns={'Population (2016 est.)[8]':'Population'},inplace=True)
    cities['NFL']=cities['NFL'].str.replace('\[.*\]','',regex=True)
    cities['NFL']=cities['NFL'].str.extract('([a-zA-Z0-9]+)')
    cities.dropna(subset=['NFL'],inplace=True)
    cities['NFL'][cities['NFL']=='GiantsJets']='Giants,Jets'
    cities['NFL'][cities['NFL']=='RamsChargers']='Rams,Chargers'
    cities['NFL'][cities['NFL']=='49ersRaiders']='49ers,Raiders'
    cities['NFL_ratio']=0
    for y in cities['NFL']:
            Win=0
            Loss=0
            for r in y.split(','):
                n=cities.loc[cities['NFL']==y].index.values
                for x in nfl_df2['team']:
                        m = nfl_df2.loc[nfl_df2['team']==x].index.values
                        if r in x and len(y)>0:
                    #print("y:{}, x:{}".format(y,x))
                            Win=Win+float (nfl_df2.loc[m,'W'].values[0])
                            Loss=Loss+float (nfl_df2.loc[m,'L'].values[0])
                            ratio=Win/(Win+Loss)
                            cities.loc[n,'NFL_ratio']=ratio
                            break
    cities['Population']=cities['Population'].astype(int)
    population_by_region = list(cities['Population']) # pass in metropolitan area population from cities
    win_loss_by_region = list(cities['NFL_ratio']) # pass in win/loss ratio from nfl_df in the same order as cities["Metropolitan area"]

    assert len(population_by_region) == len(win_loss_by_region), "Q4: Your lists must be the same length"
    assert len(population_by_region) == 29, "Q4: There should be 29 teams being analysed for NFL"

    return stats.pearsonr(population_by_region, win_loss_by_region)[0]
nfl_correlation()

0.004922112149349428

## Question 5
In this question I would like you to explore the hypothesis that **given that an area has two sports teams in different sports, those teams will perform the same within their respective sports**. How I would like to see this explored is with a series of paired t-tests (so use [`ttest_rel`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_rel.html)) between all pairs of sports. Are there any sports where we can reject the null hypothesis? Again, average values where a sport has multiple teams in one region. Remember, you will only be including, for each sport, cities which have teams engaged in that sport, drop others as appropriate. This question is worth 20% of the grade for this assignment.

In [47]:
import pandas as pd
import numpy as np
import scipy.stats as stats
import re

In [48]:
mlb_df=pd.read_csv("mlb.csv")
nhl_df=pd.read_csv("nhl.csv")
nba_df=pd.read_csv("nba.csv")
nfl_df=pd.read_csv("nfl.csv")
cities_old=pd.read_html("wikipedia_data.html")[1]
cities_old=cities_old.iloc[:-1,[0,3,5,6,7,8]]

In [49]:
cities_old

,Metropolitan area,Population (2016 est.)[8],NFL,MLB,NBA,NHL
0,New York City,20153634,GiantsJets[note 1],YankeesMets[note 2],KnicksNets,RangersIslandersDevils[note 3]
1,Los Angeles,13310447,RamsChargers[note 4],DodgersAngels,LakersClippers,KingsDucks
2,San Francisco Bay Area,6657982,49ersRaiders[note 6],GiantsAthletics,Warriors,Sharks[note 7]
3,Chicago,9512999,Bears[note 8],CubsWhite Sox,Bulls[note 9],Blackhawks
4,Dallas–Fort Worth,7233323,Cowboys,Rangers,Mavericks,Stars
5,"Washington, D.C.",6131977,Redskins,Nationals[note 10],Wizards[note 11],Capitals
6,Philadelphia,6070500,Eagles,Phillies[note 12],76ers,Flyers[note 13]
7,Boston,4794447,Patriots[note 14],Red Sox[note 15],Celtics,Bruins
8,Minneapolis–Saint Paul,3551036,Vikings,Twins,Timberwolves,Wild[note 16]
9,Denver,2853077,Broncos,Rockies,Nuggets[note 17],Avalanche[note 18]
10,Miami–Fort Lauderdale,6066387,Dolphins,Marlins,Heat,Panthers
11,Phoenix,4661537,Cardinals,Diamondbacks,Suns,Coyotes
12,Detroit,4297617,Lions,Tigers[note 20],Pistons[note 21],Red Wings
13,Toronto,5928040,— [note 22],Blue Jays,Raptors[note 23],Maple Leafs
14,Houston,6772470,Texans[note 24],Astros,Rockets,—
15,Atlanta,5789700,Falcons,Braves,Hawks,[note 25]
16,Tampa Bay Area,3032171,Buccaneers,Rays,—,Lightning
17,Pittsburgh,2342299,Steelers,Pirates,[note 27],Penguins[note 28]
18,Cleveland,2055612,Browns[note 29],Indians[note 30],Cavaliers[note 31],[note 32]
19,Seattle,3798902,Seahawks,Mariners,[note 33],[note 34]
20,Cincinnati,2165139,Bengals,Reds[note 35],[note 36],—
21,Kansas City,2104509,Chiefs,Royals[note 37],[note 38],[note 39]
22,St. Louis,2807002,[note 40],Cardinals[note 41],[note 42],Blues[note 43]
23,Baltimore,2798886,Ravens[note 45],Orioles[note 46],[note 47],—
24,Charlotte,2474314,Panthers,—,Hornets[note 49],—
25,Indianapolis,2004230,Colts,[note 50],Pacers[note 51],—
26,Nashville,1865298,Titans,—,—,Predators
27,Milwaukee,1572482,[note 53],Brewers[note 54],Bucks,—
28,New Orleans,1268883,Saints,—,Pelicans[note 55],—
29,Buffalo,1132804,Bills[note 56],[note 57],[note 58],Sabres
30,Montreal,4098927,—,[note 59],—,Canadiens
31,Vancouver,2463431,—,—,[note 60],Canucks
32,Orlando,2441257,—,—,Magic,—
33,Portland,2424955,—,—,Trail Blazers,—
34,Columbus,2041520,—,—,—,Blue Jackets
35,Calgary,1392609,—,—,—,Flames
36,Ottawa,1323783,—,—,—,Senators
37,Edmonton,1321426,—,—,—,Oilers
38,Salt Lake City,1186187,—,—,Jazz,—
39,Winnipeg,778489,—,—,—,Jets[note 61]
40,San Diego,3317749,[note 62],Padres,[note 63],—
41,San Antonio,2429609,[note 64],—,Spurs,—
42,Sacramento,2296418,—,—,Kings,—
43,Las Vegas,2155664,[note 6],—,—,Golden Knights
44,Jacksonville,1478212,Jaguars,—,—,—
45,Oklahoma City,1373211,—,—,Thunder[note 68],—
46,Memphis,1342842,[note 69],—,Grizzlies,—
47,Raleigh,1302946,—,—,—,Hurricanes
48,Green Bay,318236,Packers,—,—,—
49,Hamilton,747545,—,—,—,[note 71]
50,Regina,236481,—,—,—,—

In [50]:
def nhl_cities():
    cities=pd.DataFrame(cities_old, copy=True) 
    cities['NHL']=cities['NHL'].str.extract('([a-zA-Z0-9 \.]*)')
    nhl_df['team']=nhl_df['team'].str.extract('([a-zA-Z0-9 \.]*)')
    nhl_df2=nhl_df[nhl_df['year']==2018]
    cities.rename(columns={'Population (2016 est.)[8]':'Population'},inplace=True)
    cities['NHL'][cities['NHL']=='RangersIslandersDevils']='Rangers,Islanders,Devils'
    cities['NHL'][cities['NHL']=='KingsDucks']='Kings,Ducks'
    cities['NHL']=cities['NHL'].str.extract('([a-zA-Z0-9\s\,]+)')
    cities.dropna(subset=['NHL','Population'],inplace=True)
    nhl_df2=nhl_df2[1:]
    nhl_df2['W']=nhl_df2['W'].str.extract('([0-9]+)')
    nhl_df2['L']=nhl_df2['L'].str.extract('([0-9]+)')
    nhl_df2['L']=nhl_df2['L'].astype(float)
    nhl_df2.dropna(subset=['L','W'],inplace=True)
    cities['ratio']=0
    for y in cities['NHL']:
        Win=0
        Loss=0
        for r in y.split(','):
                n=cities.loc[cities['NHL']==y].index.values
                for x in nhl_df2['team']:
                    m=nhl_df2.loc[nhl_df2['team']==x].index.values
                    if r in x and len(y)>0:
                        #print("y:{}, x:{}".format(y,x))
                        Win=Win+float(nhl_df2.loc[m,'W'].values[0])
                        Loss=Loss+float(nhl_df2.loc[m,'L'].values[0])
                        ratio=Win/(Win+Loss)
                        cities.loc[n,'ratio']=ratio
                        break
    cities['Population']=cities['Population'].astype(float)
    
    population_by_region = list(cities['Population']) # pass in metropolitan area population from cities
    win_loss_by_region = list(cities['ratio']) # pass in win/loss ratio from nhl_df in the same order as cities["Metropolitan area"]

    assert len(population_by_region) == len(win_loss_by_region), "Q1: Your lists must be the same length"
    assert len(population_by_region) == 28, "Q1: There should be 28 teams being analysed for NHL"
    
    return cities
def nba_cities():
    cities=pd.DataFrame(cities_old, copy=True)
    cities2=pd.DataFrame(cities, copy=True)
    cities2.columns = cities2.columns.str.strip()
    cities2['NBA']=cities2['NBA'].str.replace('\[.*\]','',regex=True)
    cities2['NBA']=cities2['NBA'].str.extract('([A-Za-z0-9\s]+)')
    cities2['NBA'][cities2['NBA']=='KnicksNets']='Knicks,Nets'
    cities2['NBA'][cities2['NBA']=='LakersClippers']='Lakers,Clippers'
    
    assert('Population (2016 est.)[8]' in cities2.columns)
    cities2.rename(columns={'Population (2016 est.)[8]':'Population'},inplace=True)
    cities2.dropna(subset=['NBA','Population'],inplace=True)   
    #cities2.dropna(subset=['NBA','Population (2016 est.)[8]'],inplace=True)   
    nba_df2=nba_df
    nba_df2['team']=nba_df2['team'].str.extract('([a-zA-Z\s]+)')
    nba_df2=nba_df2[nba_df2['year']==2018]
    nba_df2['team'][nba_df2['team']=='Philadelphia ']='Philadelphia 76ers'  
    #cities2.rename(columns={'Population (2016 est.)[8]':'Population'},inplace=True)
    cities2=cities2[0:28]
    cities2['ratio_NBA']=0
    for y in cities2['NBA']:
        Win=0
        Loss=0
        for r in y.split(','):
                if len(y)>0:
                    n=cities2.loc[cities2['NBA']==y].index.values
                    
                for x in nba_df2['team']:
                    m=nba_df2.loc[nba_df2['team']==x].index.values
                    if r in x and len(y)>0:
                    #print("y:{}, x:{}".format(y,x))
                        Win=Win+float(nba_df2.loc[m,'W'].values[0])
                        Loss=Loss+float(nba_df2.loc[m,'L'].values[0])
                        ratio=Win/(Win+Loss)
                        cities2.loc[n,'ratio_NBA']=ratio
                        break   
    cities2['Population']=cities2['Population'].astype(int)
    population_by_region = list(cities2['Population']) # pass in metropolitan area population from cities
    win_loss_by_region = list(cities2['ratio_NBA']) # pass in win/loss ratio from nba_df in the same order as cities["Metropolitan area"]

    assert len(population_by_region) == len(win_loss_by_region), "Q2: Your lists must be the same length"
    assert len(population_by_region) == 28, "Q2: There should be 28 teams being analysed for NBA"

    return cities2
def mlb_cities(): 
    cities=pd.DataFrame(cities_old, copy=True)
    mlb_df2=pd.DataFrame(mlb_df[mlb_df['year']==2018],copy=True)
    cities.columns = cities.columns.str.strip()
    cities.rename(columns={'Population (2016 est.)[8]':'Population'},inplace=True)
    cities['MLB']=cities['MLB'].str.replace('\[.*\]','',regex=True)
    cities['MLB']=cities['MLB'].str.extract('([A-Za-z0-9\s]+)')
    cities.dropna(subset=['MLB'],inplace=True)
    cities['MLB'][cities['MLB']=='YankeesMets']='Yankees,Mets'
    cities['MLB'][cities['MLB']=='CubsWhite Sox']='Cubs,White Sox'
    cities['MLB'][cities['MLB']=='DodgersAngels']='Dodgers,Angels'
    cities['MLB'][cities['MLB']=='GiantsAthletics']='Giants,Athletics'
    cities['MLB_ratio']=0
    for y in cities['MLB']:
        Win=0
        Loss=0
        for r in y.split(','):
                n=cities.loc[cities['MLB']==y].index.values
                for x in mlb_df['team']:
                        m=mlb_df.loc[mlb_df['team']==x].index.values
                        if r in x and len(y)>0:
                    #print("y:{}, x:{}".format(y,x))
                            Win=Win+float(mlb_df.loc[m,'W'].values[0])
                            Loss=Loss+float(mlb_df.loc[m,'L'].values[0])
                            ratio=Win/(Win+Loss)
                            cities.loc[n,'MLB_ratio']=ratio
                            break
    cities['Population']=cities['Population'].astype(int)
    population_by_region = list(cities['Population']) # pass in metropolitan area population from cities
    win_loss_by_region = list(cities['MLB_ratio']) # pass in win/loss ratio from mlb_df in the same order as cities["Metropolitan area"]
    assert len(population_by_region) == len(win_loss_by_region), "Q3: Your lists must be the same length"
    assert len(population_by_region) == 26, "Q3: There should be 26 teams being analysed for MLB"
    return cities
def nfl_cities(): 
    cities=pd.DataFrame(cities_old, copy=True)
    cities.columns = cities.columns.str.strip()
    nfl_df2=pd.DataFrame(nfl_df[(nfl_df['year']==2018) & (nfl_df['L'].str.contains('([0-9]+)'))],copy=True)
    nfl_df2['team']=nfl_df2['team'].str.extract('([a-zA-Z\s]+)')
    cities.rename(columns={'Population (2016 est.)[8]':'Population'},inplace=True)
    cities['NFL']=cities['NFL'].str.replace('\[.*\]','',regex=True)
    cities['NFL']=cities['NFL'].str.extract('([a-zA-Z0-9]+)')
    cities.dropna(subset=['NFL'],inplace=True)
    cities['NFL'][cities['NFL']=='GiantsJets']='Giants,Jets'
    cities['NFL'][cities['NFL']=='RamsChargers']='Rams,Chargers'
    cities['NFL'][cities['NFL']=='49ersRaiders']='49ers,Raiders'
    cities['NFL_ratio']=0
    for y in cities['NFL']:
            Win=0
            Loss=0

            for r in y.split(','):
                    n=cities.loc[cities['NFL']==y].index.values
                    for x in nfl_df2['team']:
                            m = nfl_df2.loc[nfl_df2['team']==x].index.values
                            if r in x and len(y)>0:
                        #print("y:{}, x:{}".format(y,x))
                                Win=Win+float (nfl_df2.loc[m,'W'].values[0])
                                Loss=Loss+float (nfl_df2.loc[m,'L'].values[0])
                                ratio=Win/(Win+Loss)
                                cities.loc[n,'NFL_ratio']=ratio
                                break
    cities['Population']=cities['Population'].astype(int)
    population_by_region = list(cities['Population']) # pass in metropolitan area population from cities
    win_loss_by_region = list(cities['NFL_ratio']) # pass in win/loss ratio from nfl_df in the same order as cities["Metropolitan area"]

    assert len(population_by_region) == len(win_loss_by_region), "Q4: Your lists must be the same length"
    assert len(population_by_region) == 29, "Q4: There should be 29 teams being analysed for NFL"
    
    return cities

In [51]:
MLB_NFL=mlb_cities().merge(nfl_cities(),on='Metropolitan area')
MLB_NFL
p_mlbnfl=list(stats.ttest_rel(MLB_NFL['NFL_ratio'],MLB_NFL['MLB_ratio']))[1]

In [52]:
NBA_NHL=nba_cities().merge(nhl_cities(),on='Metropolitan area')
p_nbanhl=list(stats.ttest_rel(NBA_NHL['ratio'],NBA_NHL['ratio_NBA']))[1]

In [53]:
MLB_NHL=mlb_cities().merge(nhl_cities(),on='Metropolitan area')
p_mlbnhl=list(stats.ttest_rel(MLB_NHL['ratio'],MLB_NHL['MLB_ratio']))[1]

In [54]:
MLB_NBA=mlb_cities().merge(nba_cities(),on='Metropolitan area')
p_mlbnba=list(stats.ttest_rel(MLB_NBA['ratio_NBA'],MLB_NBA['MLB_ratio']))[1]

In [55]:
NFL_NHL=nfl_cities().merge(nhl_cities(),on='Metropolitan area')
p_nflnhl=list(stats.ttest_rel(NFL_NHL['ratio'],NFL_NHL['NFL_ratio']))[1]

In [56]:
NFL_NBA=nfl_cities().merge(nba_cities(),on='Metropolitan area')
p_nflnba=list(stats.ttest_rel(NFL_NBA['NFL_ratio'],NFL_NBA['ratio_NBA']))[1]

In [57]:
sports = ['NFL', 'NBA', 'NHL', 'MLB']
p_values = pd.DataFrame({'NFL':[np.nan,p_nflnba,p_nflnhl,p_mlbnfl],'NBA':[p_nflnba,np.nan,p_nbanhl,p_mlbnba],'NHL':[p_nflnhl,p_nbanhl,np.nan,p_mlbnhl],'MLB':[p_mlbnfl,p_mlbnba,p_mlbnhl,np.nan]}, index=sports)
p_values

          NFL       NBA       NHL       MLB
NFL       NaN  0.941792  0.030959  0.802384
NBA  0.941792       NaN  0.022316  0.951046
NHL  0.030959  0.022316       NaN  0.000712
MLB  0.802384  0.951046  0.000712       NaN

In [58]:
import pandas as pd
import numpy as np
import scipy.stats as stats
import re

mlb_df=pd.read_csv("mlb.csv")
nhl_df=pd.read_csv("nhl.csv")
nba_df=pd.read_csv("nba.csv")
nfl_df=pd.read_csv("nfl.csv")
cities_old=pd.read_html("wikipedia_data.html")[1]
cities_old=cities_old.iloc[:-1,[0,3,5,6,7,8]]

def sports_team_performance():
    def nhl_cities():
        cities=pd.DataFrame(cities_old, copy=True) 
        cities['NHL']=cities['NHL'].str.extract('([a-zA-Z0-9 \.]*)')
        nhl_df['team']=nhl_df['team'].str.extract('([a-zA-Z0-9 \.]*)')
        nhl_df2=nhl_df[nhl_df['year']==2018]
        cities.rename(columns={'Population (2016 est.)[8]':'Population'},inplace=True)
        cities['NHL'][cities['NHL']=='RangersIslandersDevils']='Rangers'
        cities['NHL'][cities['NHL']=='Rangers']='Rangers Islanders Devils'
        cities['NHL'][cities['NHL']=='KingsDucks']='Kings'
        cities['NHL'][cities['NHL']=='Kings']='Kings Ducks'
        cities['NHL']=cities['NHL'].str.extract('([a-zA-Z\s]+)')
        cities.dropna(subset=['NHL','Population'],inplace=True)
        nhl_df2=nhl_df2[1:]
        nhl_df2['W']=nhl_df2['W'].str.extract('([0-9]+)')
        nhl_df2['L']=nhl_df2['L'].str.extract('([0-9]+)')
        nhl_df2['L']=nhl_df2['L'].astype(float)
        nhl_df2.dropna(subset=['L','W'],inplace=True)
        cities['ratio']=0
        for y in cities['NHL']:
            Win=0
            Loss=0
            for r in y.split():
                n=cities.loc[cities['NHL']==y].index.values
                for x in nhl_df2['team']:
                    m=nhl_df2.loc[nhl_df2['team']==x].index.values
                    if r in x and len(y)>0:
                        #print("y:{}, x:{}".format(y,x))
                        Win=Win+float(nhl_df2.loc[m,'W'].values[0])
                        Loss=Loss+float(nhl_df2.loc[m,'L'].values[0])
                        ratio=Win/(Win+Loss)
                        cities.loc[n,'ratio']=ratio
                        break
        cities['Population']=cities['Population'].astype(float)
        
        population_by_region = list(cities['Population']) # pass in metropolitan area population from cities
        win_loss_by_region = list(cities['ratio']) # pass in win/loss ratio from nhl_df in the same order as cities["Metropolitan area"]

        assert len(population_by_region) == len(win_loss_by_region), "Q1: Your lists must be the same length"
        assert len(population_by_region) == 28, "Q1: There should be 28 teams being analysed for NHL"
        
        return cities
    def nba_cities():
        cities=pd.DataFrame(cities_old, copy=True)
        cities2=pd.DataFrame(cities, copy=True)
        cities2.columns = cities2.columns.str.strip()
        cities2['NBA']=cities2['NBA'].str.replace('\[.*\]','',regex=True)
        cities2['NBA']=cities2['NBA'].str.extract('([A-Za-z0-9\s]+)')
        cities2['NBA'][cities2['NBA']=='KnicksNets']='Knicks Nets'
        cities2['NBA'][cities2['NBA']=='LakersClippers']='Lakers Clippers'
        
        assert('Population (2016 est.)[8]' in cities2.columns)
        cities2.rename(columns={'Population (2016 est.)[8]':'Population'},inplace=True)
        cities2.dropna(subset=['NBA','Population'],inplace=True)   
        #cities2.dropna(subset=['NBA','Population (2016 est.)[8]'],inplace=True)   
        nba_df2=nba_df
        nba_df2['team']=nba_df2['team'].str.extract('([a-zA-Z\s]+)')
        nba_df2=nba_df2[nba_df2['year']==2018]
        nba_df2['team'][nba_df2['team']=='Philadelphia ']='Philadelphia 76ers'  
        #cities2.rename(columns={'Population (2016 est.)[8]':'Population'},inplace=True)
        cities2=cities2[0:28]
        cities2['ratio_NBA']=0
        for y in cities2['NBA']:
            Win=0
            Loss=0
            for r in y.split():
                if len(y)>0:
                    n=cities2.loc[cities2['NBA']==y].index.values
                    
                for x in nba_df2['team']:
                    m=nba_df2.loc[nba_df2['team']==x].index.values
                    if r in x and len(y)>0:
                    #print("y:{}, x:{}".format(y,x))
                        Win=Win+float(nba_df2.loc[m,'W'].values[0])
                        Loss=Loss+float(nba_df2.loc[m,'L'].values[0])
                        ratio=Win/(Win+Loss)
                        cities2.loc[n,'ratio_NBA']=ratio
                        break   
        cities2['Population']=cities2['Population'].astype(int)
        population_by_region = list(cities2['Population']) # pass in metropolitan area population from cities
        win_loss_by_region = list(cities2['ratio_NBA']) # pass in win/loss ratio from nba_df in the same order as cities["Metropolitan area"]

        assert len(population_by_region) == len(win_loss_by_region), "Q2: Your lists must be the same length"
        assert len(population_by_region) == 28, "Q2: There should be 28 teams being analysed for NBA"

        return cities2
    def mlb_cities(): 
        cities=pd.DataFrame(cities_old, copy=True)
        mlb_df2=pd.DataFrame(mlb_df[mlb_df['year']==2018],copy=True)
        cities.columns = cities.columns.str.strip()
        cities.rename(columns={'Population (2016 est.)[8]':'Population'},inplace=True)
        cities['MLB']=cities['MLB'].str.replace('\[.*\]','',regex=True)
        cities['MLB']=cities['MLB'].str.extract('([A-Za-z0-9\s]+)')
        cities.dropna(subset=['MLB'],inplace=True)
        cities['MLB'][cities['MLB']=='YankeesMets']='Yankees,Mets'
        cities['MLB'][cities['MLB']=='CubsWhite Sox']='Cubs,White Sox'
        cities['MLB'][cities['MLB']=='DodgersAngels']='Dodgers,Angels'
        cities['MLB'][cities['MLB']=='GiantsAthletics']='Giants,Athletics'
        cities['MLB_ratio']=0
        for y in cities['MLB']:
            Win=0
            Loss=0
            for r in y.split(','):
                n=cities.loc[cities['MLB']==y].index.values
                for x in mlb_df['team']:
                        m=mlb_df.loc[mlb_df['team']==x].index.values
                        if r in x and len(y)>0:
                    #print("y:{}, x:{}".format(y,x))
                            Win=Win+float(mlb_df.loc[m,'W'].values[0])
                            Loss=Loss+float(mlb_df.loc[m,'L'].values[0])
                            ratio=Win/(Win+Loss)
                            cities.loc[n,'MLB_ratio']=ratio
                            break
        cities['Population']=cities['Population'].astype(int)
        population_by_region = list(cities['Population']) # pass in metropolitan area population from cities
        win_loss_by_region = list(cities['MLB_ratio']) # pass in win/loss ratio from mlb_df in the same order as cities["Metropolitan area"]
        assert len(population_by_region) == len(win_loss_by_region), "Q3: Your lists must be the same length"
        assert len(population_by_region) == 26, "Q3: There should be 26 teams being analysed for MLB"
        return cities
    def nfl_cities(): 
            cities=pd.DataFrame(cities_old, copy=True)
            cities.columns = cities.columns.str.strip()
            nfl_df2=pd.DataFrame(nfl_df[(nfl_df['year']==2018) & (nfl_df['L'].str.contains('([0-9]+)'))],copy=True)
            nfl_df2['team']=nfl_df2['team'].str.extract('([a-zA-Z\s]+)')
            cities.rename(columns={'Population (2016 est.)[8]':'Population'},inplace=True)
            cities['NFL']=cities['NFL'].str.replace('\[.*\]','',regex=True)
            cities['NFL']=cities['NFL'].str.extract('([a-zA-Z0-9]+)')
            cities.dropna(subset=['NFL'],inplace=True)
            cities['NFL'][cities['NFL']=='GiantsJets']='Giants,Jets'
            cities['NFL'][cities['NFL']=='RamsChargers']='Rams,Chargers'
            cities['NFL'][cities['NFL']=='49ersRaiders']='49ers,Raiders'
            cities['NFL_ratio']=0
            for y in cities['NFL']:
                    Win=0
                    Loss=0
                    for r in y.split(','):
                        n=cities.loc[cities['NFL']==y].index.values
                        for x in nfl_df2['team']:
                                m = nfl_df2.loc[nfl_df2['team']==x].index.values
                                if r in x and len(y)>0:
                            #print("y:{}, x:{}".format(y,x))
                                    Win=Win+float (nfl_df2.loc[m,'W'].values[0])
                                    Loss=Loss+float (nfl_df2.loc[m,'L'].values[0])
                                    ratio=Win/(Win+Loss)
                                    cities.loc[n,'NFL_ratio']=ratio
                                    break
            cities['Population']=cities['Population'].astype(int)
            population_by_region = list(cities['Population']) # pass in metropolitan area population from cities
            win_loss_by_region = list(cities['NFL_ratio']) # pass in win/loss ratio from nfl_df in the same order as cities["Metropolitan area"]

            assert len(population_by_region) == len(win_loss_by_region), "Q4: Your lists must be the same length"
            assert len(population_by_region) == 29, "Q4: There should be 29 teams being analysed for NFL"
            
            return cities
    MLB_NFL=mlb_cities().merge(nfl_cities(),on='Metropolitan area')
    p_mlbnfl=list(stats.ttest_rel(MLB_NFL['NFL_ratio'],MLB_NFL['MLB_ratio']))[1]
    NBA_NHL=nba_cities().merge(nhl_cities(),on='Metropolitan area')
    p_nbanhl=list(stats.ttest_rel(NBA_NHL['ratio'],NBA_NHL['ratio_NBA']))[1]
    MLB_NHL=mlb_cities().merge(nhl_cities(),on='Metropolitan area')
    p_mlbnhl=list(stats.ttest_rel(MLB_NHL['ratio'],MLB_NHL['MLB_ratio']))[1]
    MLB_NBA=mlb_cities().merge(nba_cities(),on='Metropolitan area')
    p_mlbnba=list(stats.ttest_rel(MLB_NBA['ratio_NBA'],MLB_NBA['MLB_ratio']))[1]
    NFL_NHL=nfl_cities().merge(nhl_cities(),on='Metropolitan area')
    p_nflnhl=list(stats.ttest_rel(NFL_NHL['ratio'],NFL_NHL['NFL_ratio']))[1] 
    NFL_NBA=nfl_cities().merge(nba_cities(),on='Metropolitan area')
    p_nflnba=list(stats.ttest_rel(NFL_NBA['NFL_ratio'],NFL_NBA['ratio_NBA']))[1]
    sports = ['NFL', 'NBA', 'NHL', 'MLB']
    p_values = pd.DataFrame({'NFL':[np.nan,p_nflnba,p_nflnhl,p_mlbnfl],'NBA':[p_nflnba,np.nan,p_nbanhl,p_mlbnba],'NHL':[p_nflnhl,p_nbanhl,np.nan,p_mlbnhl],'MLB':[p_mlbnfl,p_mlbnba,p_mlbnhl,np.nan]}, index=sports)
    
    assert abs(p_values.loc["NBA", "NHL"] - 0.02) <= 1e-2, "The NBA-NHL p-value should be around 0.02"
    assert abs(p_values.loc["MLB", "NFL"] - 0.80) <= 1e-2, "The MLB-NFL p-value should be around 0.80"
    return p_values

In [59]:
sports_team_performance()

          NFL       NBA       NHL       MLB
NFL       NaN  0.941792  0.030959  0.802384
NBA  0.941792       NaN  0.022316  0.951046
NHL  0.030959  0.022316       NaN  0.000712
MLB  0.802384  0.951046  0.000712       NaN